### ISSUE TITLE
Arter ikke behandlet for Svalbard (eller omvendt)

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#10]
Hvis man søker på en art som ikke finnes på Svalbard, bør man uansett få et treff som sier noe om arten på Svalbard (innsyn og API). 

Mulig løsning: 

- For arter i artsgrupper vurdert for Svalbard (karplanter, lav, fugler, pattedyr, spretthaler (NB fisk?)), kan arten settes til NA, Arten er ikke etablert på Svalbard. **Oppdatert**: Jeg tror ikke vi har grunnlag for å si at arten ikke finnes på Svalbard. I tillegg så presentere noe som ikke er kvalitetssikret av ekspertene. Konklusjon: Vi setter aldri en art til NA (med mindre det er gjort av eksperten).
- Arter i andre artsgrupper: Alle arter settes til NE med begrunnelse: Arten hører til en artsgruppe som ikke er vurdert for Svalbard. NB: I de mange tilfeller vet vi ikke om arten finnes på Svalbard eller ikke, bør det komme fram? **Oppdatert**: Enig med Kristine: det vil være misvisende å sette til NE siden det kan gi inntrykk av at arten finnes på Svalbard. 

Hvis man søker ulv eller Canis lupus og avgrenser søket til Svalbard bør svaret skille på om manglende treff skyldes at navnet ikke finnes eller om arten ikke er behandlet. Man kan få beskjed: 1) Søket ga ingen treff i artsnavnebasen 2) Arten er ikke behandlet for Svalbard. Det samme gjelder hvis man søker på Svalbardarter og avgrenser til Norge.

**Comment by KristineLund** [comment]
Er litt skeptisk til den mulige løsningen- MÅ alle artene ha en kategori i begge vurderingsområdene? Vet ikke hvordan diskusjonen rundt dette har vært, men ser for meg at det lett kan skje feil om vi sleiver til å sette en art til NA eller NE basert på vår info uten kvalitetssikring fra ekspertene. Da blir jo denne svært forenklede "behandlingen" i etterkant sidestilt med ekspertenes behandling av arter til NA og NE, og det blir umulig å skille mellom de to. (+ En hel del artskapitler må antageligvis skrives om mtp. behandlede arter.) 

Hvis absolutt MÅ ha treff også på ting som ikke gir særlig mening, eks. ulv på Svalbard, er det ikke bedre om det bare dukker opp en helt enkel markør som sier "arten er ikke behandlet for Svalbard" uten å gå nærmere inn på årsak/kategori?

**Comment by KristineLund** [comment]
Diskusjonen fortsetter i den mer generelle issue #87
