### ISSUE TITLE
Sette domene for cookie i drift

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#1039]
Endre domene for cookie slik at den fungerer uavhengig av www i url

bakgrunn:

det er lov med både https://**www**.artsdatabanken.no/ og https://artsdatabanken.no/ på hjemmesidene
cookie settes på domenet man bruker når man besøker sidene (som regel uten www, virker det som)

lenken som sendes for å bekrefte epost går til **www**.artsdatabanken.no (hentes via kode og antagelig blir "www" siden den er konfigurert først på iis) - man blir da bekreftet og husket på det domenet..

når man senere besøker sidene uten **www**, så er man ikke lengre bekreftet og husket - om må gå gjennom prosessen på nytt

**Comment by steinho** [comment]
Cookie domain kan og settes i kode - til "artsdatabanken.no" - og ville da fungert for både med og uten. trippelwoff...

f.eks.: 
            Context.Response.Cookies.Append(validationCookieName, emailValidation.Guid.ToString(), new CookieOptions
            {
                Expires = DateTime.Now.AddMonths(1),
                Domain = "artsdatabanken.no"
            });
