### ISSUE TITLE
Issue i taksonomiske grupper i filteret

### ISSUE THREAD

**Issue by tanjakofodpetersen** [Artsdatabanken/assessments-frontend#1055]
Helene fant et issue filteret på artsgruppe (noe som jeg har surret i).
Gruppen Maxillopoda under Krepsdyr i ikke anerkjent i navnebasen. De artene som skulle ha ligget der hører til under hoppekreps (Copepoda) og Rankefortinger (Thecostraca/Cirripedia).
I tillegg bør havedderkopper vel teknisk sett legges inn under krepsdyr.

Vedlagt fil med oversikt over artene som er påvirket
[TaksonomiTrøbbel.csv](https://github.com/Artsdatabanken/assessments-frontend/files/10825049/TaksonomiTrobbel.csv)

@matssa er den til deg?

**Comment by androiddev001** [comment]
Yeah

**Comment by steinho** [comment]
> Helene fant et issue filteret på artsgruppe (noe som jeg har surret i). Gruppen Maxillopoda under Krepsdyr i ikke anerkjent i navnebasen. De artene som skulle ha ligget der hører til under hoppekreps (Copepoda) og Rankefortinger (Thecostraca/Cirripedia). I tillegg bør havedderkopper vel teknisk sett legges inn under krepsdyr.
> 
> Vedlagt fil med oversikt over artene som er påvirket [TaksonomiTrøbbel.csv](https://github.com/Artsdatabanken/assessments-frontend/files/10825049/TaksonomiTrobbel.csv)
> 
> @matssa er den til deg?

Hør med Toril/Artsnavnebase før vi eventuelt gjør avvikende tilpasninger i FAB.
