### ISSUE TITLE
Man må godta vilkår i innsynet to ganger

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#1063]
Skal man legge inn en kommentar i innsynet må man godta vilkårene to ganger. Først når man oppgir e-postadresse og så igjen når man skal sende inn kommentaren. Det må være tilstrekkelig om den dukker opp når man skal sende inn kommentaren

**Comment by matssa** [comment]
Innsynet er nå over og vi lukker denne.
