### ISSUE TITLE
Noen arter dukker opp med kategori NS, og noen mangler latinsknavnid

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#11]
Det er et visst samsvar, men ikke helt

![bilde](https://user-images.githubusercontent.com/17450081/121163632-3e696c00-c84f-11eb-8ba7-b3a39d9baa97.png)

**Comment by helemork** [comment]
Det kan se ut som case (i hverftall for noen) er at arten er vurdert under et annet navn. Vi må nøste opp hvordan dette skal vises i api

**Comment by eirikn-artsdatabanken** [comment]
virker ikke som dette er issue lengre

ingen kategorier med "NS": 
https://assessments-fe.test.artsdatabanken.no/api/Species2021?$count=true&$apply=groupby((Category),aggregate($count%20as%20Count))

ingen vurderinger uten latinsknavnid  ("ScientificNameId"): https://assessments-fe.test.artsdatabanken.no/api/Species2021?$count=true&$filter=ScientificNameId%20eq%20null

disse forsvant nok siden vi ikke lengre tar med slettede vurderinger og de som var lagt inn for testing
