### ISSUE TITLE
Se over og oppdater info på habitat-siden

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#110]
Fra visningssiden lenkes det til  [denne habitat-siden](https://assessments-fe.test.artsdatabanken.no/species/habitat ). Behøver revisjon. Trenger litt hjelp fra noen som har vært med helt fra starten av @SiriKasperdatter eller @SnorresKongesaga.

Per 1. sept lenkes den inn her:
![image](https://user-images.githubusercontent.com/25904198/131664611-87996df3-0201-45ed-9a81-83cff2bec576.png)

**Comment by SiriKasperdatter** [comment]
Holder på å oppdatere metodedelen om naturtyper. Ikke helt enkelt det heller når man ikke var med på å utarbeide disse endringene. 
Men legger merke til at det står **"inkludert driftvoller"** på Fjæresonssystemer, men hovedtypen er ikke listet under. T24 Driftvoll er derimot listet under Kysttilknyttede fastmarksystemer. I veilederen er T24 Driftvoll koblet med Kysttilknyttede fastmarkssystemer. 
Skal "inkludert driftvoller" fjernes fra beskrivelsen til Fjæresonesystemer, @SnorresKongesaga?

**Comment by SnorresKongesaga** [comment]
Ja, driftvoller er fastmark og skal inn under Kysttilknyttede fastmarkssystemer, ikke fjæresone

**Comment by SnorresKongesaga** [comment]
Ny tekst:
Norsk rødliste for arter 2021 

Hovedhabitat 

Publisert: 24. november 2021. 

Hovedhabitatet er de viktigste naturtypene for artens overlevelse i Norge. Hvert hovedhabitat er avgrenset etter hovedtypene på natursystemnivået i Naturtyper i Norge (NiN 2.0).  

Arter kan forekomme i mange forskjellige naturtyper og spesielt mobile arter som fugler kan påtreffes i nær sagt alle naturtyper. I Rødlista er bare de leveområdene som er viktigst for arten angitt. Det innebærer at habitatet skal være relevant for mer enn 20 % av populasjonen. Mer informasjon om hvordan de ulike hovedhabitatene er avgrenset finnes i veilederen til rødlistevurdering (pdf) og nærmere beskrivelse av hovedtypene finnes på Artsdatabankens nettsider.

**Comment by helemork** [comment]
@tovelitovela ref. drupal vs. fastboende side.

Linket opp de to undersidene habitat og artsgruppe som ble laget før sommeren
. 
Disse ble først og fremst satt opp for at det skal være lettere å korrekturlese at ting er korrekt i den komponenten som dukker opp på vurderingssiden :) 

Hvordan det hele av flyt mellom infosider, filtersider og drupalsider skal henge sammen er en flyt det hadde vært fint å få info på før vi begynner å korrigere introtekstene i noen grad.

Jeg synes jo personlig (og der tror jeg at @steinho er enig) at alt burde komme fra en kilde men vises i samme løsning. Kilden kan i teorien være drupal, men det er mer behagelig å jobbe med om den finnes internt i prosjektet. Men @tovelitovela nevnte at det er en visjon på gang om sider i drupal og deres fremstilling. Dette blir jo et prosjekt å få integrert visuelt med resten, men det er i teorien mulig. Kan de av dere som har sterke meninger melde fra så vi kan få tatt et oppklarende møte på temaet?

**Comment by tovelitovela** [comment]
Jeg plager deg med et møte i dag, om du har tid @helemork :D

**Comment by helemork** [comment]
Disse sidene har nå blitt slettet ettersom det hele ender opp i Drupal.
Lukker derfor denne.
