### ISSUE TITLE
Presentasjon av spretthalevurderinger på visningssiden

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#114]
Det er ønskelig med en slags markering på vurderingene av spretthaler så det kommer tydelig fram at de ikke er revidert til Rødlista 2021. Eksempel-spretthaler: 12929, 4401

"Ikke revidert siden 2010" eller noe lignende

Får også være obs på hvordan kategori mm. presenteres på visningssiden

**Comment by steinho** [comment]
@helemork - informasjonen ligger på modellen som AssessmentYear - hvis lik 2010 - vurdert i 2010

@KristineLund - denne er ikke oppdatert til nytt årstall for de nye vurderingen (ligger bare 2015 der pluss 2021 for hydrioder og arter som ble lagt til. Stemmer at alle andre artsgrupper er blitt 'revidert' i 2021?

**Comment by helemork** [comment]
Har nå satt inn en enkel presentasjonsstreng så det står på siden.
Om vi ønsker en mer overtydelig og estetisk fremstilling, kan vi godt se på det når flere kritiske ting er ferdigstilt. Velger derfor å endre prioritering på denne fremfor å sette den som lukket.

**Comment by helemork** [comment]
Denne er å anse som ferdig.
