### ISSUE TITLE
FA statistikk (filter) fane graf 1: antall arter/risikokategori

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#1153]
Vi skal ha figurer som skal endres basert på filtering i FA lista som da vises i den "Statistikk" fanen ("Figurer" fanen etter nytt oppsett). Første av dem skal vise antall arter i hvert risikokategori (ekskludert NR artene).

NB: Følgende arter skal ekskluderes fra figuren ( tillegg til NR-arter): AlienSpeciesCategory == "TaxonEvaluatedAtAnotherLevel"

![image](https://user-images.githubusercontent.com/25793207/234553999-539c22a3-dadc-4993-acab-27015b7f2116.png)

@AneMarlene  skal skrive figurtekst for dette i tillegg som skal følge med.

**Comment by AneMarlene** [comment]
@mats. Her er tittel og figurtekst til grafen. Tittelen plasseres over figuren, figurteksten plasseres under. 

1. tittel: Antall vurderinger per risikokategori
2. figurtekst: En vurdering av en fremmed art resulterer i kun én risikokategori. Det totale antallet i figuren tilsvarer derfor antall vurderinger i utvalget, som her er **n** vurderinger. Av disse er **x** vurdert å være høyrisikoarter, dvs. de utgjør enten en høy risiko, eller en svært høy risiko for norsk natur.

Merknad til punkt 2: **n** og **x** byttes ut med totalantallet i utvalget, og antallet HI + SE -arter i utvalget, 'respectively'.
Merk også at alle figurene må lages som listeobjekter. Se issue #1168.
