### ISSUE TITLE
FA statistikk (filter) fane graf 3: antall arter/artsgruppe

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#1159]
Her er graf nummer 3 for filter/statistikk fane med antall arter per organismegruppe
Denne figuren ønsker vi sortert etter antall treff i utvalget per artsgruppe (slik som vist i figuren).

NB: Følgende arter skal ekskluderes fra figuren ( tillegg til NR-arter): AlienSpeciesCategory == "TaxonEvaluatedAtAnotherLevel"

![bilde](https://user-images.githubusercontent.com/25793207/234908928-3c6f7ff4-1052-40da-ac72-7740bafd9e77.png)

@AneMarlene  kommer igjen med figurtekst for dette som skal følge med.

**Comment by AneMarlene** [comment]
Figurtittel: Antall vurderinger per artsgruppe

Figurtekst: Antall vurderinger i hver artsgruppe. Utvalget ditt omfatter **n** vurderinger.
