### ISSUE TITLE
FA statistikk (filter) fane graf 4: Antall arter per avgjørende kriterier

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#1161]
Vi skal ha figurer som skal endres basert på filtering i FA lista som da vises i den "Statistikk" fanen ("Figurer" fanen etter nytt oppsett). Fjerde av dem skal vise antall arter per avgjørende kriterier. Se forslag til bilde her (minus rutenett på bakgrunn og x-akse)

NB: 
- På y-aksen bruker du CriteriaLetter (Value og DisplayName), men A og B settes sammen (se figur). 
- Dette er _avgjørende_ kriterier, og det som skal vises figuren er altså kun kriterier som finnes i DecisiveCriteria for arten (det følger at NK-arter er ekskludert, ettersom de har DecisiveCriteria == "1,1"). 
- Følgende arter skal ekskluderes fra figuren ( tillegg til NR-arter): AlienSpeciesCategory == "TaxonEvaluatedAtAnotherLevel". 

![bilde](https://user-images.githubusercontent.com/25793207/234912709-645fae36-9ef9-4533-8a95-5b791c086efc.png)

**Comment by AneMarlene** [comment]
Her kommer tittel og figurtekst: 

Tittel: 
Antall vurderinger per avgjørende kriterium

Figurtekst (merk: **x** er her antall observasjoner til sammen i figuren): 
Artens risiko i norsk natur vurderes mot totalt ni kriterier, A - I: tre kriterier, A - C, beskriver artens invasjonspotensial og seks kriterier, D – I, beskriver artens økologiske effekter. Kriteriene med høyeste skår for invasjonspotensial og økologisk effekt er avgjørende for kategori. Én vurdering kan ha flere avgjørende kriterier, og totalantallet kan derfor overstige antall vurderinger i utvalget. Ettersom arter uten kjent risiko skårer 1 på samtlige kriterier, er arter i kategorien _ingen kjent risiko_ ekskludert. Utvalget ditt omfatter **n** vurderinger med totalt **x** avgjørende kriterier (**y** vurderinger i utvalget har _ingen kjent risiko_).
