### ISSUE TITLE
FA statistikk (filter) fane graf 5A: effekt på truete/sjeldne naturtyper

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#1162]
Vi skal ha figurer som skal endres basert på filtering i FA lista som da vises i den "Statistikk" fanen ("Figurer" fanen etter nytt oppsett). Femte av dem skal vise antall arter som har påvirkning på truete eller sjeldne naturtype (disse vises på det aggrekerte nivå "tema"). Disse bør helst være organisert slik at det med flest arter stå høyes om det ikke bli for vanskelig når man endrer datagrunnlag med filtrering.

NB: Følgende arter skal ekskluderes fra figuren ( tillegg til NR-arter): AlienSpeciesCategory == "TaxonEvaluatedAtAnotherLevel"

![bilde](https://user-images.githubusercontent.com/25793207/234913671-e2dc48b7-3b67-4834-9765-9e27f53b8dd2.png)

@AneMarlene for tekster!

**Comment by AneMarlene** [comment]
Denne figuren er nr 1 av 2 figurer som vil høre til under hovedtittelen "Arter i truede eller sjeldne naturtyper". Mao,

Hovedtittel (for to figurer): Arter i truede eller sjeldne naturtyper

Figurtittel: Antall vurderinger per hovedøkosystem eller landform

Figurtekst: Antall vurderinger per hovedøkosystem eller landform med truede eller sjeldne naturtyper (Rødlista for Naturtyper 2018). Den vurderte arten kan være observert i et hovedøkosystem eller landform i dag, eller den forventes å kolonisere hovedøkosystemet eller landformen i fremtiden.  Hvert hovedøkosystem og landform telles kun én gang per vurdering, selv om en art kan finnes i flere truede eller sjeldne naturtyper innenfor hver (se neste figur). Utvalget ditt omfatter **n** vurderinger.
