### ISSUE TITLE
FA statistikk (filter) fane graf 6 A: spredningsveier til natur

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#1163]
Vi skal ha figurer som skal endres basert på filtering i FA lista som da vises i den "Statistikk" fanen ("Figurer" fanen etter nytt oppsett). Den sjette figuren skal vise antall arter per spredningsvei på overordne nivå. Igjen, disse vil vi helst ha organisert med høyeste søyle øverst. 

NB: Følgende arter skal ekskluderes fra figuren ( tillegg til NR-arter): AlienSpeciesCategory == "TaxonEvaluatedAtAnotherLevel"

![bilde](https://user-images.githubusercontent.com/25793207/234914974-1418f8dd-36c5-4661-8a3c-30afe9113045.png)

@AneMarlene skal skrive teksten

**Comment by AneMarlene** [comment]
Denne figuren er nr 1 av 2 figurer som vil høre til under hovedtittelen "Spredningsveier til norsk natur". Mao,

Hovedtittel (for to figurer): Spredningsveier til norsk natur

Figurtittel: Antall vurderinger per hovedspredningsvei til norsk natur

Figurtekst: Antall vurderinger i utvalget per hovedspredningsvei til natur. En fremmed art kan ha flere hovedspredningsveier til naturen, og det totale antallet kan derfor overstige antall vurderinger. Utvalget ditt omfatter **n** vurderinger
