### ISSUE TITLE
Bransh for å produsere PDF av topp-cards

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#1177]
Til lansering ønsker vi en PFD med (et utvalg) fremmedarter. For å redusere omfanget (antall sider..), ønsker vi kun å inkludere toppcardet for hver art. 

Det er fint om f.eks. undertegnede kan gå inn i branshen og enkelt endre på utvalget som skal med, men i utgangspunktet tenker vi alle risikovurderte arter (ikke AlienSpeciesCategory == "NR"). 

Ønskene for fila: 
- Vi ønsker ikke NR-arter, altså ikke AlienSpeciesCategory == "NR"
- Vi ønsker ikke ha med informasjon fra venstremarg (se foretrukket utseende i vedlegg)
- Vi ønsker et utvalg av informasjonen fra høyremargen: Tidligere kategorier, hvorvidt den står i forbudslista, samt ETT bilde om arten har bilder (se foretrukket utseende i vedlegg)
- Vi ønsker at noen lenker endres til å se ut som vanlig tekst, andre lenker fjernes (se foretrukket utseende i vedlegg)
- Vi ønsker to vurderinger per side (se foretrukket utseende i vedlegg)
- Om mulig ønsker vi en første side med plass til noe tekst (ca 0.5 side) og innholdsfortegnelse (om det ikke er mulig i branshen/mye jobb, så legger vi på det etterpå). 

- Vi ønsker at vurderingene sorteres i rekkefølge slik: 
1. Dørstokkarter (AlienSpeciesCategory is DoorKnocker or EffectWithoutReproduction)
    - Sorteres innad etter risikokategori (SE først, så HI, PH, LO og NK)
2.  Reproduserende arter (AlienSpeciesCategory is AlienSpecie or RegionallyAlien)
    -  Sorteres innad etter risikokategori (SE først, så HI, PH, LO og NK)

[PDF-versjon av vurderinger (til lansering)_kun_artseks.docx](https://github.com/Artsdatabanken/assessments-frontend/files/11487316/PDF-versjon.av.vurderinger.til.lansering._kun_artseks.docx)

**Comment by matssa** [comment]
Lukker dette issuet nå, da det er ferdig.
