### ISSUE TITLE
Arter uten 2021 kategori (løse tråder)

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#12]
Noen arter behandlet tidligere har blitt slettet fra 2021 basen. Dette gjelder i hovedsak arter som ikke finnes i Norge. Vanligvis slettes ikke arter fra basen uten at siste kategori gir en forklaring på hvorfor arten slettes. Vi ønsker å begrense antall arter som ikke finnes i Norge i lista derfor slettes slike vurderinger.

Hvis man søker på en slik art, bør det komme tydelig fram (i tabellen?) at siste kategori er fra f.eks. 2015. Går man inn på vurderingen så står det (forhåpentligvis) Arten har ikke dokumentert forekomst i Norge (NA)

Vi har noen eksempel på at vurderte arter har blitt slettet fordi man ikke lenger anser at det er en "god" art (mulig eksempel: Trametes velutina). Hva gjør vi med 2015-vurderinger som er et taksonomisk blindspor, dvs. navnet er ikke lenger gyldig?

Hva med f.eks. karplanten Aethusa cynapium elata  (M.Bieb.) Nyman. Det er synonym for Aethusa cynapium cynapium, men vurderingen er ikke flyttet fordi det er mer enn en navneendring og vurderingsenhetene er så ulike. Siden elata er et synonym vil man få treff på gyldig navn. 

NB spretthaler er ikke revidert siden 2010

**Comment by SiriKasperdatter** [comment]
Snorres punkt nr. 3, når taksonet som tidligere har blitt behandlet ikke lengre anses som en god art, og dermed ikke er gyldig i navnebase, henger også sammen med #24, pri 3.
