### ISSUE TITLE
Endringer i I-kriterie tabell

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#1240]
I fremmedartslista for arter som har I-kriterie som avgjørende vises dette i veldig brei tabell. Det er små endringer vi ønsker i dette: 
- [x] Kolonne overskrift: "Er arten en nøkkelart?" -> "Nøkkelart?", "Kategori i Rødlista 2021" -> "Kategori Rødlista 2021" hvor "Rødlista 2021" kommer i samme linje.
- [x]  Tekst i overskriftene og radene venstrejustert

**Comment by AneMarlene** [comment]
@matssa endringen på tittelkolonne for nøkkelart kan gjøres på alle tabeller.

**Comment by AneMarlene** [comment]
punkt 2 ble fikses i arbeid jeg og Stein gjorde i går.
