### ISSUE TITLE
"Nulle ut" CriteriaSummarized på vurderinger med Category == LCº

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#125]
Behøver en metode i transformeringen for å erstatte verdier på CriteriaSummarized med "" for arter i kategorien LCº. Det er fordi vi ikke ønsker å presentere det som at en LC-art har gjeldende kriterier. OBS: kun LCº (gjelder omtrent 14 vurderinger)

**Comment by steinho** [comment]
La til i transformasjonen

**Comment by helemork** [comment]
@KristineLund  Men i teorien skal vel hverken LC, NA eller NE arter inneholde CriteriaSummarized?
Det hadde kanskje vært greit å ha en sjekk for det også? Eller er du sikker på at det aldri vil kunne inntreffe?

**Comment by KristineLund** [comment]
Stemmer det @helemork, godt tenkt! Jeg trodde det fantes sikkerhetsmekanismer så det aldri ville inntreffe, men jaggu var det en LC-art som hadde sneket seg til en verdi på CriteriaSummarized gitt! 3226

**Comment by helemork** [comment]
Jeg tror vi kanskje skal være forsiktige med å anta sikkerhetsmekansmer i RL. For selv om de (forhåpentligvis) er på plass i selve innleggingsapplikasjonen kan jo ting ha kommet med fra 2015 om det ikke renses og overskrives såvidt jeg har forsått.

**Comment by steinho** [comment]
@KristineLund - skal jeg endre lastingen av produksjonsdata slik at dette felte blankes ut for alle disse kategoriene: LC, NA eller NE?

**Comment by KristineLund** [comment]
> @KristineLund - skal jeg endre lastingen av produksjonsdata slik at dette feltet blankes ut for alle disse kategoriene: LC, NA eller NE?

Ja takk :)
