### ISSUE TITLE
Ikke ta med Ekspertgruppe "Moser (Svalbard)" i datagrunnlaget

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#127]
Ekspertgruppe "Moser (Svalbard)" skal ikke vises på hjemmesiden eller i api'et

De bør ikke tas med når vi henter data fra databasen (før transformeringen)
(fra før tar vi ikke med vurderinger med "IsDeleted = true" og "Ekspertgruppe = Testarter")

Dette gjøres i et eget prosjekt som foreløpig ikke er lagt til i dette repo'et, det ligger her: https://github.com/Artsdatabanken/assessments-api/tree/main/Assessments.Transformation
(bør også legge det til og lage noen instrukser på hvordan det fungerer)

https://github.com/Artsdatabanken/assessments-frontend/commit/af1a739405d93e828ff0f6bd190599dbbf40a53d

**Comment by steinho** [comment]
Endelig løsning kommer via issue #134
