### ISSUE TITLE
Bytte ikon for taxon-sidene

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#1349]
Skal bli sånn her: 
![image](https://github.com/Artsdatabanken/assessments-frontend/assets/15391193/cf324c0d-51b3-4f50-8a73-554565d5633e)
@tovelitovela vet muligens mer om dette.

**Comment by tovelitovela** [comment]
Det skal erstatte bildet som er over "til artssiden" på vurderingssidene f.eks https://artsdatabanken.no/lister/fremmedartslista/2023/1866
