### ISSUE TITLE
Bilde for artsgruppe pigghuder mangler

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/assessments-frontend#135]
Søk på f.eks. ulv - fører til treff på bl.a. pigghuder

Krasjer da på test:
 Connection id "0HMBODG592JNU", Request id "0HMBODG592JNU:00000002": An unhandled exception was thrown by the application.
      System.Collections.Generic.KeyNotFoundException: The given key 'Pigghuder' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at AspNetCore.Views_Redlist_List_partials__ListView.<>c__DisplayClass13_1.<<ExecuteAsync>b__0>d.MoveNext() in /src/Assessments.Frontend.Web/Views/Redlist/List/partials/_ListView.cshtml:line 52

**Comment by Superviken** [comment]
Denne har jeg vel allerede laget?

**Comment by helemork** [comment]
Ja, du ble linket inn for å gi meg lenke tror jeg, @Superviken

**Comment by Superviken** [comment]
Har jeg ikke sendt i teams?

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Helene ***@***.***>
Sendt: Tuesday, November 16, 2021 3:52:23 PM
Til: Artsdatabanken/assessments-frontend ***@***.***>
Kopi: Åshild Stolsmo Viken ***@***.***>; Mention ***@***.***>
Emne: Re: [Artsdatabanken/assessments-frontend] Bilde for artsgruppe pigghuder mangler (#135)


Ja, du ble linket inn for å gi meg lenke tror jeg, @Superviken<https://github.com/Superviken>
