### ISSUE TITLE
Fremmedartslista: Transformer horisontskannede arter og vis fram vurderingene i fremmedartslista

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#1397]
Arter som ikke gikk videre fra horisontskanningen er foreløpig ikke å finne på våre nettsider. De ligger gjemt i FAB. Vi ønsker å publisere resultatene fra horisontskanningen for disse artene. 

1. Transformer artene (oppgave 1 til 3 er i issue #1415). De er foreløpig luket ut i TransformAlienSpecies.cs (se skjermdump). Her må det gjøres en justering på koden som sørger for at kun ferdigstilte vurderinger transformeres (per nå i L. 233 i develop sin versjon av TransformAlienSpecies.cs). Dette må beholdes for artene som ligger under risikovurdering i FAB så vi ikke transformerer vurderinger derfra med EvaluationStatus "inprogress", men må ikke gjelde artene som ligger under horisontskanningen ettersom ingen av de er ferdigstilte (og vil derfor ikke transformeres om kodesnutten omfatter disse). Justeringen kan gjøres ved å tilføre et argument: !fa4.HorizonDoScanning, slik at arter under horisontskanningen transformeres selv om de ikke er ferdigstilte.

![image](https://github.com/Artsdatabanken/assessments-frontend/assets/58254444/c7b45601-88dd-4cad-8e49-6feb38f5143e)

2. Mapping: Opprett en ny verdi for AlienSpeciesCategory for artene. Den nye kategorien skal hete "HorizonScannedButNoRiskAssessment", og den skal vises som "Horisontskannet" (norsk) og "Horizon scanned" (engelsk). 
3. Mapping: Feltene HorizonEstablismentPotential og "HorizonEcologicalEffect" må med fra FAB. De har tre mulige verdier hver (se skjermdump). 

![image](https://github.com/Artsdatabanken/assessments-frontend/assets/58254444/bf179d9b-3b6a-481a-9988-7cd1f931deda)

4. Siteringsfil for vurderinger må byttes ut med en oppdatert fil som inkluderer siteringsregel for vurderings-IDer fra horisontskanningen. #1416 
5. Artene skal dukke opp under "Ikke risikovurdert"-filteret i FAL og alle artene skal ha kategori NR. #1417 
6. Visning av vurderingene. Se issue #1425  for visning.

**Comment by matssa** [comment]
Vi har en branch hvor vi har startet litt med dette allerede: https://github.com/Artsdatabanken/assessments-frontend/tree/feature/horizonScanned
