### ISSUE TITLE
Artsside - La det taksonomiske nivået form (f.) henvises til som "takson", og ikke som "former", samt henvis til hybrid som hybrid

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#1399]
Alle steder på vurderingssiden hvor "form" brukes for å beskrive noe om taksonet, ønsker vi at det bare skal stå "takson". Eksempel fra cardet: 

![image](https://github.com/Artsdatabanken/assessments-frontend/assets/58254444/478bc76a-fbf7-4b4b-a411-9b54f72e43bf)

På de samme stedene ønsker vi også at hybrider (på artsnivået, altså ikke underarter, varieteter eller former) henvises til som en hybrid og ikke som en art.

**Comment by matssa** [comment]
Vi bør ha en forklaring på hva et takson er. Dette er ikke sånt som folk flest kjenner til. Kanskje ha en setning om det på listesiden i ingressen? 
![image](https://github.com/Artsdatabanken/assessments-frontend/assets/15391193/942a0e99-9c41-49d1-97ad-821b38e1df5c)
