### ISSUE TITLE
Kategori med grader trenger forklaring

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#157]
Kategori med grader trenger en forklaring på hva grader betyr.
Det trengs også å la kategorier med grader få samme farge på kategorien som andre (se bilde)
![vu_grader](https://user-images.githubusercontent.com/15391193/134148780-f0927a36-e59f-4f0f-a4cf-28a2dafab322.PNG)

**Comment by KristineLund** [comment]
Kategori med grader er kategori etter nedgradering/oppgradering av den opprinnelige kategorien (satt etter kriteriene) for vurderingsområdet. Denne justeringen blir gjort når utdøingsrisiko i vurderingsområdet er sterkt påvirket av bestander i naboregioner.

**Comment by helemork** [comment]
... men hvor skal den vises? 
Har nå lagt til forklaringen i glossary, men usikker på hvor denne teksten skal dukke opp?
