### ISSUE TITLE
Kriterier bør samles én plass 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#17]
I innsynsløsningen er kriteriene hardkodet inn flere steder.
Målet er å samle all info om kriterie og hvordan det skal presenteres i f.eks en JSON eller databasemodell.
Fritekst bør leveres fra en kilde, ikke skrives rett inn i koden.
Dette bør også komprimere og gjøre selve kriteriefremstillingene vesentlig mer oversiktlige.

**Comment by KristineLund** [comment]
[Her ](https://artsdatabankenno-my.sharepoint.com/:w:/g/personal/kristine_bjornaas_artsdatabanken_no/EdmzBZ4-W7tEt29Q7_CVZxIBsMfgxLARVpso6CZwee7wWA?e=6XOhcH)er det jeg opprinnelig skrev om informasjonen som står under "Om gjeldende kriterier" - Denne delen har blitt justert gjennom mange issues, så den ble ikke helt sånn til slutt.  

Tekstene i forklaringsboksene rundtom er[ herfra](https://artsdatabankenno-my.sharepoint.com/:w:/g/personal/kristine_bjornaas_artsdatabanken_no/ETpgZ8SKJ29Hs7z-lixAF4QB9H88BKZWg-UTNvbvjCDANg?e=Aqu7CN)

Det som står under "Oppsummering" har med [denne](https://artsdatabankenno-my.sharepoint.com/:w:/g/personal/kristine_bjornaas_artsdatabanken_no/EemsGBmuFVBIjUtgKNgHm3ABnCMfADvHBC6LTmtVauTMlg?e=6hRdrA) spekken å gjøre. 

Det som står under "Informasjon om vurderingen" stammer delvis [herfra](https://artsdatabankenno-my.sharepoint.com/:w:/g/personal/kristine_bjornaas_artsdatabanken_no/ETqKymNvXzlMkjaxkrnpa4wBdgYOg5StvrPU4IKKbZfhDw?e=DW7ZfJ). For mange NA, NE og LC-arter er det eneste info som finnes i vurderingen, så jeg tenkte det var nyttig med litt "lesbar" tekst i fulle setninger. 

Hvordan skal vi gå fram for å lage "oppslags-kilder" som du foreslår? Jeg kan selvfølgelig hjelpe til å sette ting i system, men har ikke helt oversikt over det som foregår på baksida (mulige kombinasjoner av variabler, hvilke som overstyrer hvilke), så jeg har bare gjettet meg til det meste hittil...

**Comment by helemork** [comment]
All tekst tilhørende kriterier er nå samlet i denne json-fila.
https://github.com/Artsdatabanken/assessments-frontend/blob/master/Assessments.Frontend.Web/Views/Test/partials_2021/Kriterier_2021/kriterier.json
