### ISSUE TITLE
Presentasjon av kriterier

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#18]
[Edit for å unngå duplikat]

- [x] Formatere og splitte opp kriteriestreng for å få ut relevante nivå av kriterier 
- [x] Hente ut all relevant tekst fra en felles jsonfil - #17
- [x] Hente ut alle øvre nivå kriterier
- [x] Hente ut alle underkriterier
- [x] Hente ut alle options 
- [x] Hente ut suboptions for C-kriteriet (utelukkende for C2)
- [x] Hente ut subkategori for options for B-kriteriet (Underliggende a, b og c)
- [x] Forbedre tekstene i jsonfila når det er lett å se hvordan det ender opp
- [x] Hente ut info om tall som tidligere lå i komponentene min max probable interval, hvorav det nå er totalt nye datatyper etter transformajsonen.

---
Gode eksempelart-id'er:
19978 (c-kriteriet)
14469 (b-kriteriet)
24069 (a-kriteriet)
37836 (kaotisk kriterie, mye b)

[orginal]: 
Bygge videre på innsynet 2021, men vi (les Tove) ønsker en kortversjon

**Comment by KristineLund** [comment]
Denne er vel nærmest identisk med issue #17 som Helene holder på med? Eller?

**Comment by tovelitovela** [comment]
Nært beslektet, men ikke identisk. Vi kan se nærmere på den når #17 er i land :)

**Comment by helemork** [comment]
Tekstene er nå flyttet ut, så planen er å få hovedvisningen til å bli lettere å forstå. Her vil det være to faser: 
1) Få ut alt innholdet osv. 
2) Ta en runde med kommunikasjon på hvordan det bør vises optimalt sett.

**Comment by helemork** [comment]
Issuen lot seg ikke flytte, se detaljer på:
https://github.com/Artsdatabanken/assessments-api/issues/16

**Comment by helemork** [comment]
Jeg tror vil lukker denne etter siste merge, men tar forebehold om at det bør komme endringer i visning av suboption-data, og vi bør sikre at vi har korrekte endringer i tekst.
