### ISSUE TITLE
Hovedhabitat MainHabitat kortnavn 

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#185]
Er ønskelig med kortere navn på MainHabitat i filter, statistikkvisning (flere plasser?)
Lage oppslagstabell i datakilden for verdi og beskrivelse (=kortnavn)?

F.eks. at "Fastmarksskogsmark" vises som "Skog" der det er hensiktsmessig.

**Comment by helemork** [comment]
Habitat henter vi hovedsaklig fra JSON fila vår da de inneholder mye mer data enn bare dette.
Det hadde vært optimalt for oss å få inn "shortnames" der.
https://github.com/Artsdatabanken/assessments-frontend/blob/master/Assessments.Frontend.Web/wwwroot/json/habitat.json

**Comment by KristineLund** [comment]
la til shortname i en branch av habitat.json [https://github.com/Artsdatabanken/assessments-frontend/blob/habitat_add_shortname/Assessments.Frontend.Web/wwwroot/json/habitat.json](https://github.com/Artsdatabanken/assessments-frontend/blob/habitat_add_shortname/Assessments.Frontend.Web/wwwroot/json/habitat.json)
