### ISSUE TITLE
Filter bug

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#193]
- [x] Habitatfilter på "Semi-naturlig fastmark" fungerer ikke. 
- [x] filter på stormaneter er ikke koblet til maneter
- [x] Semi-naturlig mark fungerer heller ikke

**Comment by helemork** [comment]
relatert til shortnames?

**Comment by matssa** [comment]
> relatert til shortnames?

Nei, det var der nok fra før
