### ISSUE TITLE
Tekst under "Årsak til endring av kategori"

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#201]
Nå ligger det inne engelsk tekst på [vurderingssiden](https://assessments-fe.test.artsdatabanken.no/species/772):

- [x] Endre til følgende norske begrunnelser (jeg har ikke de engelske begrepene): 

Ny tolkning av tidligere data
Endret (ny eller annen) kunnskap
Reell populasjonsendring
Ikke vurdert: NA/NE art 2015
Endring i vurderingsområde
Endrete kriterier eller tilpasning til regler
Ikke vurdert: NA/NE art 2021
Endret taksonomisk status
Arten nyoppdaget eller nybeskrevet for landet
Ikke vurdert: NA/NE art 2010

**Comment by eirikn-artsdatabanken** [comment]
legger til metode som henter beskrivelsen fra enum her:
https://github.com/Artsdatabanken/assessments-frontend/blob/cbaf5c0b69022bf31df2bfb55266373e601f522d/Assessments.Mapping/Models/Species/CategoryChangeReason.cs#L5
