### ISSUE TITLE
"naturtypeHovedenhet": "IsSnøBreforland" er egentlig bare "Is og snø" ...ikke breforland

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#22]
Litt usikker på hvor jeg skal putte denne issuen, så bare flytt den dit det passer. 

Hovedhabitat "IsSnøBreforland" bør vises som "Is og snø", i alle fall utad. Breforland hører inn under en annet hovedhabitat, "ArktiskAlpineJorddektFastmark". Til innsynet hadde vi nok bare en midlertidig løsning på dette, men det hadde vært kjekt med en mer permanent fiks. 

Vi gikk gjennom alle vurderinger på "breforland"-arter og flyttet dem på riktig hovedhabitat etter NiN før innsynet.

**Comment by helemork** [comment]
https://github.com/Artsdatabanken/assessments-frontend/blob/master/Assessments.Frontend.Web/Views/Test/partials_2021/habitat.json

All info om habitater ligger nå i denne fila. Dere må gjerne endre den ved behov :) eventuelt sende meg ønsker til endring.
