### ISSUE TITLE
Oppdatere lenker til informasjonssider som er up-to date

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#279]
- [x] Lenke for fremmedartsinformasjon
- [x] Lenke til metode
- [ ] Lenke i inkluderingskriteriet
- [x] Ekspertkomite-lenke må oppdateres
- [ ] kriterier i c1
- [ ] Helt sikkert flere, ta en titt.
- [x] URL til ordliste for kriterier
- [x] URL til metodedel for kriterier
- [ ] Interne url'er i kriterier
Denne må naturlig nok vente til lenkene eksisterer. :)

**Comment by KristineLund** [comment]
> * [ ]  Lenke for fremmedartsinformasjon https://www.artsdatabanken.no/Pages/241513/Fleire_artar_bankar_paa (dørstokkart) <- denne er allerede riktig
> * [ ]  Lenke til metode
> * [ ]  Lenke i inkluderingskriteriet
> * [ ]  Ekspertkomite-lenke må oppdateres
> * [ ]  kriterier i c1
> * [ ]  Helt sikkert flere, ta en titt.
> * [ ]  URL til ordliste for kriterier
> * [ ]  URL til metodedel for kriterier
> * [ ]  Interne url'er i kriterier
>   Denne må naturlig nok vente til lenkene eksisterer. :)

**Comment by SiriKasperdatter** [comment]
> * [x]  Lenke for fremmedartsinformasjon
> * [ ]  Lenke til metode
https://www.artsdatabanken.no/Pages/314252/Metode
> * [ ]  Lenke i inkluderingskriteriet
**Hva er dette?**
> * [ ]  Ekspertkomite-lenke må oppdateres
https://www.artsdatabanken.no/Pages/314251/Ekspertkomit_ene
> * [ ]  kriterier i c1
> * [ ]  Helt sikkert flere, ta en titt.
> * [ ]  URL til ordliste for kriterier
https://www.artsdatabanken.no/Pages/314252/Metode#316490
> * [ ]  URL til metodedel for kriterier
https://www.artsdatabanken.no/Pages/314252/Metode#316484
> * [ ]  Interne url'er i kriterier
>   Denne må naturlig nok vente til lenkene eksisterer. :)

**Comment by KristineLund** [comment]
> * [x]  Lenke for fremmedartsinformasjon
> * [x]  Lenke til metode
> * [ ]  Lenke i inkluderingskriteriet -- hvis du mener som i "hvorfor er arten vurdert for Rødlista?" er det https://www.artsdatabanken.no/Pages/316561/Nasjonale_tilpasninger
> * [x]  Ekspertkomite-lenke må oppdateres
> * [ ]  kriterier i c1
> * [ ]  Helt sikkert flere, ta en titt.
> * [x]  URL til ordliste for kriterier
> * [x]  URL til metodedel for kriterier
> * [ ]  Interne url'er i kriterier
>   Denne må naturlig nok vente til lenkene eksisterer. :)

**Comment by SiriKasperdatter** [comment]
- [ ] Habitat 
https://www.artsdatabanken.no/Pages/314252/Metode#316492
