### ISSUE TITLE
Plassering av antall som er med i utvalget

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#291]
Se forslag (ikke bruk mine farger). @helemork: kan du foreslå layout?
![image](https://user-images.githubusercontent.com/59921838/137912984-05ea03ed-bd85-4605-b415-2baf620a9102.png)

**Comment by helemork** [comment]
Men hvor skal vi putte det på litenskjerm?
og såfremst ikke brukeren aktivt har valgt art fjellrev er det riktige å putte "fjellrev" i boksen ikke arten. Rett og slett fordi det f.eks kan være "rein" eller "alg" osv, som ikke trenger å lede til en entydig vurdering.

**Comment by matssa** [comment]
@SnorresKongesaga slik vi gjør det nå kan vi ikke gjøre som finn på mobil. Denne måten å gjøre det på krever at vi sender en forespørsel til serveren for hvert klikk, noe vi har skrudd av for mobil for å spare mobildata.
