### ISSUE TITLE
Håndtere Svalbard vs. Norge i kart

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#298]
**KART Option 1:**
- Kartet som er nå er kartet for pattedyr. Vi burde oppdatert Norge sitt kart til å ikke ha denne kystsonen, men la regionene gå inn til svalbard. Det kan forbli et kart om path til havområdene redigeres bak kystsonen, og kystsonen ligger over. Og så skjules hele svalbard kystsone for norges arter og svalbard-arter som ikke er pattedyr. 
- Legenden bør inneholde svalbard. Det bør komme ved endreing i relatert issue, #296 

**KART Option 2:**
- Burde vi vist et zooma inn svaldbarkart heller på svalbard-artene? (med- og uten kystsone)
- Kart nr. 1 mp likevel oppdateres tilsvarende
- Nytt svalbard med kystsonekart må lages/ekstraheres
- Legenden blir nå liten og søt og inneholder utelukkende svalbard.

**Comment by helemork** [comment]
Ja, men det telles i statistikken slik det er nå, så om områder utenfor området skal fjernes, BØR det fjernes i transformasjonen før dataene kommet inn til kartet i det heletatt.

Så her vil jeg egentlig ha input fra flere av dere, @SnorresKongesaga  og @SiriKasperdatter 

- Skal vi fjerne all data som er utenfor vurderingsområdet i en vurdering? Det er jo å endre innlagt data, men samtidig har de jo ikke følgt retningslinjene
- Skal vi leave it as is? vise de de har lagt inn og la ekspertene ta støyten for dårlig statistikk og farger utenfor området? Det er jo pent.

P.S. Det er kort tid igjen nå, så å redigere om et eget kart for Svalbard  - det er veldig doable, men hvordan er det egentlig prioritert? Jeg synes kanskje det er ganske viktig, men innser jo det kan være uenighet her. F.eks jeg ville prioritert det over B-kriteriets underkategori-data - da jeg tror flere ville hatt nytte av det, men samtigig kan jo noen være svært uenig med meg der :)

**Comment by SiriKasperdatter** [comment]
Jeg er ikke helt sikker på hvilken løsning jeg heller mot, dessverre, siden fulgfolket ikke har lagt inn havområdene for Norge, men i hovedsak bare for Svalbard. 
Steinvender for Svalbard: 
![image](https://user-images.githubusercontent.com/61016662/140530724-eb90509f-b323-40be-9444-0429e63dc09c.png)
Steinvender for Norge: 
![image](https://user-images.githubusercontent.com/61016662/140530775-e0c9c693-0dbb-4b08-b2a3-5165843ceb22.png)

Hvis vi da velger å fjerne havområdene for Svalbard-vurderingen, så går vi på på et vis glipp av denne dataen. Hva tror @SnorresKongesaga?

**Comment by KristineLund** [comment]
Etter møtet 9. nov ble vi enige om å sette all regionforekomst utenfor vurderingsområdet til **ikkeKjent** allerede i transformeringen, f.eks. en art vurdert for Svalbard har ikke lov til å ha "antattUtdødd" forekomst i Fi.

Det går helt fint med samme kart og samme tekst under "Vurderingsområde og artens utbredelse" for alle Svalbard-vurderinger. Tekst fra pattedyr, altså. Vi må nesten anta at publikum skjønner at moser ikke svømmer rundt i Svalbards fjorder.
