### ISSUE TITLE
Assessmentview: fra starten tom. "Tidligere vurderinger"

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#31]
- [x] Tittel: endre fra "Norsk Rødliste for arter 2021" til "Norsk rødliste for arter 2021". (Vi bruker stor r i kortformer f.eks. "Rødlista 2021", men ikke i det fulle navnet)
- [x] Ingress (1/3): gjerne endre tekst til "Arten har blitt **behandlet** til "kategori" **for** Norsk rødliste for arter 2021 som viser arters risiko for å dø ut fra Norge." Behandlet er en mer alt-inkluderende beskrivelse, jfr. at NA og NE ikke er "vurdert" for Rødlista. Vi syndet litt mot dette på innsynet... Eller hva tror du @SiriKasperdatter?
![image](https://user-images.githubusercontent.com/25904198/124459185-30473680-dd8e-11eb-810e-d9306cfa754e.png)
- [x] Ingress (2/3): vi skriver vanligvis kategori på formen "_nær truet_ NT" og "_ikke egnet_ NE"
- [x] "Rødlistekategori"-tittel: ikke alle kategorier er rødlistekategorier, så det blir mer passende om denne heter kun "Kategori"
- [x] Kategoribeskrivelsene: plis fjern formuleringene rundt sannsynlighet på E-kriteriet "(ved bruk av E-kriteriet kvantifisert til 5 % sannsynlighet for utdøing innen 100 år*)" - disse var med i veilederen ved en feiltagelse, og har bare ført til misforståelser hos publikum. Fjern gjerne også "I så fall må dette spesifiseres i tekstboksen for Oppsummering av vurderingeni RødlisteBasen." på NT- arter. Ser også at enkelte ord i tekstene er slått sammen - skriveleif eller rusk i formateringen?

[EDIT av @helemork : ] Har nå flyttet ut en del punkt til egne issues: #37, #44, #39, #41, #40 og #46.

**Comment by SiriKasperdatter** [comment]
Enig i ingresspunktet, @KristineLund! :)
