### ISSUE TITLE
Påvirkningsfaktorer

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#32]
[Edit av @helemork ]: 

- [x] Rydde opp i feil id-problematikk arvet fra 2015 og 2010
- [x] Få frem hele listen over påvirkningsfaktorene og matche inn på riktig nivå
- [x] Vise tabell inni listen
- [x] Lang og kortvarianter

--
-> #143
- [x] (Bør vi ta stilling til om vi skal vise også påvirkningene med ubetydelig omfang/alvorlighetsgrad @SiriKasperdatter @SnorresKongesaga? Stemmer selv for å vise alle.) 
- [x]  Påvirkningsfaktorer: Id(?) henger med i overskriften på enkelte av dem:
![image](https://user-images.githubusercontent.com/25904198/124469246-67bbe000-dd9a-11eb-8394-12a83237703b.png)

[Edit av @helemork ]: 
 #49, #48 #50 og #51 ble tatt ut som egne issues.

**Comment by SiriKasperdatter** [comment]
Angående påvirkningsfaktorer, her er det vel mest ryddig å gjøre som i 2015, og da ble vel alt vist. Også enig i at alt bør vises uansett. Så får vi heller ta stilling til hvordan vi gjør det i presentasjon av overordnet statistikk. 
Hva med å sortere påvirkningsfaktorene slik at det er den samme rekkefølgen?

**Comment by helemork** [comment]
Påvirkningsfaktorer vil vi komme tilbake til, per nå mangler vi en del id'er fra databasen. Etter ny transformasjon kan vi se mer hvordan vi skal presentere dem. Lar de få bli denne issuen, og tar ut de andre ønskene til egne issues.

**Comment by KristineLund** [comment]
> Påvirkningsfaktorer vil vi komme tilbake til, per nå mangler vi en del id'er fra databasen. Etter ny transformasjon kan vi se mer hvordan vi skal presentere dem. Lar de få bli denne issuen, og tar ut de andre ønskene til egne issues.

Bare vær obs når du bruker id på påvirkningsfaktorer @helemork : det kan ligge inne gamle påvirkningsfaktorer på vurderingene, og Id fra 2015 er trolig ikke helt i samsvar med ID fra 2021. Tror dessverre at noen av Id'ene fra 2015 har blitt gjenbrukt med meningsendring i 2021. Hvis du får til å sjekke Id'ene under på Påvirkning på habitat > Landbruk > Skogbruk tror jeg det er noen som har dobbel betydning. Hadde litt trøbbel med det når jeg laga statistikk og prøvde å forbedre påvirkningsfaktorer i eksporten i våres.

**Comment by helemork** [comment]
Oi, det er jo noe som er litt viktig å rydde opp i. Jeg fikk denne linken: https://rl2021api.artsdatabanken.no/api/Kode/2 av @steinho. Er den korrekt? 

Det er veldig viktig at det blir riktig også i apiet, @eirikn-artsdatabanken så spørs om også dette må bli tatt som et eget tema for en gjennomgang. - altså å sjekke at det det er riktig allerede på ditt nivå. Men jeg vil si påvirkningsfaktorer kanskje ikke er det første vi må få på plass, selv om vi må få fikset også det.

**Comment by steinho** [comment]
@KristineLund dump av alle påvirkningsfaktorer brukt på alle vurderinger aggregert på id - med de alternative tekstene som står på dem - om det varierer...

[Dump av alle - til sjekk om det er samme betydning.txt](https://github.com/Artsdatabanken/assessments-frontend/files/7136769/Dump.av.alle.-.til.sjekk.om.det.er.samme.betydning.txt)

**Comment by steinho** [comment]
Har nå transformert ImpactFactors og forsøkt rydde litt på veien, men potensielle problem gjenstår: På noen påvirkningsfaktorer har tekst endret seg mellom i hvert fall 2015 og 2021 (kanskje også lengre tilbake i tid). Jeg har tatt meg frihet til å anta at det har samme mening i 6 tilfeller - der Id på faktoren er ellers er lik:

- stående *gadd* og liggende *læger* = stående "gadd" og liggende "læger"
- Skogbruk/avvirkning = Skogbruk (kommersielt)
- Åpne hogstformer (flatehogst og frøtrehogst som også inkluderer uttak av rotvelt, råtne trær, tørrgran etc.) = Åpne hogstformer (flatehogst og frøtrestillingshogst som også inkluderer uttak av rotvelt, råtne trær, tørrgran etc.)
-  Habitatpåvirkning på ikke landbruksarealer (terrestrisk) = Habitatpåvirkning - ikke jord- eller skogbruksaktivitet (terrestrisk)
- Oppdemming / vannstandsregulering / overføring av vassdrag = Oppdemming/vannstandsregulering/overføring av vassdrag
- Tynning, vedhogst, avvirkning av spesielle type trær (gamle, hule, brannskade) = Vedhogst, avvirkning av spesielle type trær (gamle, hule, brannskade)

Dette for at begrep brukt skal bli konsistent på alle vurderingene.

Men så kommer noen jeg ikke er overbevist om er det samme - selv om ID på dem er lik - tror det potensielt er meningsendring på disse:
Id: 1.1.2.1., Over: Påvirkning på habitat, Under: Landbruk > Skogbruk (kommersielt) - Flatehogst
     1)Flatehogst
     2)Skogsdrift, hogst og skjotsel
Id: 1.1.2.2., Over: Påvirkning på habitat, Under: Landbruk > Skogbruk (kommersielt) - Skogreising/treslagskifte
     1)Skogreising/treslagskifte
     2)Plukkhogst, tynning, vedhogst
Id: 1.1.2.3., Over: Påvirkning på habitat, Under: Landbruk > Skogbruk (kommersielt) - Fjerning av dødt virke
     1)Fjerning av dødt virke
     2)Skogbrannslukking
Id: 1.2.4.1., Over: Påvirkning på habitat, Under: Habitatpåvirkning - ikke jord- eller skogbruksaktivitet (terrestrisk) > Annen påvirkning på habitat - Fjerning av dødt virke
     1)Fjerning av dødt virke
     2)Uttak av død ved (stående *gadd* og liggende *læger*)
Id: 4.2., Over: Tilfeldig mortalitet, Under:  - Andre
     1) Andre
     2) Bifangst

Jeg kunne tatt optimistisk tilnærming og tatt den som er i henhold til siste versjon brukt i produksjonsbasen 2021 - men blir i tvil her - siden ordlyden er relativt forskjellig.
Som nevnt dette er trolig data som er blitt med på vurderingene fra tidligere runder og ikke dermed ikke lagt til nå i siste runde.

Pr nå tar jeg inn originalteksten i disse tilfellene - men om vi skal lage en liste med forklaringer knytt til Id - vil begrepene her avvike og kanskje se litt rart ut.

@KristineLund og @SnorresKongesaga - må nesten se nærmere på dette - i hvert fall om noe er blitt feil øverst!
For de under som jeg oppfatter som meningsendring må vi finne ut om om de er det samme - greit nok, eller om vi introduser nye Id'er og plasserer disse i tillegg.
Om man skal kunne søke på Id'ene i api eller visningsmodul - må det være konsistent.
Det samme om man skal lage forklarende tekster knytt til Id'ene....

**Comment by SnorresKongesaga** [comment]
Vi gjorden noen endringer før 2015. Ligger en konverteringsnøkkel her: T:\alle\P_Rødliste\2015\Databasen 

Du foreslår: 
- Skogbruk/avvirkning = Skogbruk (kommersielt)

Riktig er: 
- Skogbruk/avvirkning = Skogsdrift, hogst og skjøtsel

Merk: "Skogbruk (kommersielt)" ble innført som et nytt nivå over "Skogsdrift, hogst og skjøtsel"

**Comment by SnorresKongesaga** [comment]
Del 2

Venstre = 2010, Høyre = 2015
![image](https://user-images.githubusercontent.com/59921838/133038165-925cac99-7cfa-444f-9284-8ea6957651f0.png)

**Comment by SnorresKongesaga** [comment]
Svaret på de øvrige fire, de du ikke er overbevist om ligger her:
"T:\alle\P_Rødliste\2021\Rødlistebasen\Innlegginsapplikasjonen\Annet\Konvertering påvirkning 2010- 2021.xlsx"

**Comment by KristineLund** [comment]
Var det egentlig meningen at 2010-og 2015-påvirkningsfaktorene skulle fjernes og at man skulle begynne med blanke ark i påvirknings-fanen i 2021-basen @SnorresKongesaga? For nå er vi jo i den situasjonen at vi må bruke ID OG faktor-lagt-til-år som nøkkel for å få fram en spesifikk påvirkningsfaktorstreng. Men vi har jo ikke noen faktor-lagt-til-år informasjon pr. nå (det går sikkert an å framskaffe den, men da misser vi litt av poenget med å bruke ID som jeg ser det, nemlig å spare tid...). Det beste hadde vel vært om en ID alltid betydde det samme, uansett hvilket år faktoren ble lagt til :)

**Comment by steinho** [comment]
> Var det egentlig meningen at 2010-og 2015-påvirkningsfaktorene skulle fjernes og at man skulle begynne med blanke ark i påvirknings-fanen i 2021-basen @SnorresKongesaga? For nå er vi jo i den situasjonen at vi må bruke ID OG faktor-lagt-til-år som nøkkel for å få fram en spesifikk påvirkningsfaktorstreng. Men vi har jo ikke noen faktor-lagt-til-år informasjon pr. nå (det går sikkert an å framskaffe den, men da misser vi litt av poenget med å bruke ID som jeg ser det, nemlig å spare tid...). Det beste hadde vel vært om en ID alltid betydde det samme, uansett hvilket år faktoren ble lagt til :)
> 
> konklusjon: jeg stemmer for å legge til nye Id'er på de som ikke samsvarer. Det finnes jo nok av tall å ta av her i verden :)

Vi har fått ryddet - slik at ID blir entydig. Det var ikke snakk om meningsendring - men Id'er fra 2010 som aldri var blitt korrigert til motsvarende ider i 2015 - da faktorene på ca 12 stk har blitt plassert lengre ned (og skulle da hatt ny id). Hvis alt går bra nå - vil alle påvirkningsfaktorer være etter den nye lista og ha samsvarende begrep med den.

**Comment by SnorresKongesaga** [comment]
Nei, det er ikke meningen man skal starte med blanke ark. Dette er en revisjon @steinho 
Jeg har ikke hatt noe med kodene å gjøre etter 2010. 

Jeg forstår ikke hvorfor vi fortsatt har noen påvirkningsfaktorer fra 2010 i systemet. Alt skulle i teorien blitt konvertert i 2015. Dette er ikke spretthalene som jeg først trodde. Ingen av de er påvirket av skogbruk. 

Kan dette være påvirkningsfaktorer hvor ekspertene ikke har godkjent konverteringen fra 2010 til 2015? Dvs. at de ikke skal være med? Har du en art som eksempel

**Comment by steinho** [comment]
> Nei, det er ikke meningen man skal starte med blanke ark. Dette er en revisjon @KristineLund
> Jeg har ikke hatt noe med kodene å gjøre etter 2010.
> 
> Jeg forstår ikke hvorfor vi fortsatt har noen påvirkningsfaktorer fra 2010 i systemet. Alt skulle i teorien blitt konvertert i 2015. Dette er ikke spretthalene som jeg først trodde. Ingen av de er påvirket av skogbruk.
> 
> Kan dette være påvirkningsfaktorer hvor ekspertene ikke har godkjent konverteringen fra 2010 til 2015? Dvs. at de ikke skal være med? Har du en art som eksempel

Aglaostigma gibbosum
Hygroamblystegium varium

**Comment by helemork** [comment]
Mye av det rent tekniske er nå på plass i #142 så endelig er påvirkningsfaktorene korrekte (håper jeg) og det rent praktiske er på plass.

Det resterende er ren kosmetikk, og kan settes som Pri 2.
Oppretter derfor en ny issue på dette.
Forklaring/tekst flyttes over i ny issue #143
