### ISSUE TITLE
Samhandling mellom D2 og påvirkningsfaktorer + habitattekst

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#323]
- [ ] Koble påvirkningsfaktorer opp mot D2-kriteriet
- [ ] En setning om påvirkningsfaktorer og habitat - at det er negative faktorer som ikke direkte bestemmer noe, og at det igjen kan påvirke b-kategori s. 20 ?

**Comment by SnorresKongesaga** [comment]
Vi skal ikke tillegge vurderingene tolkninger og meninger. Vi skal derfor ikke gjøre slike koblinger. En art som er vurdert etter D2 kan ha en kombinasjon av pågående nedgang og trussel, og vi vet ikke hvem som er hvem
