### ISSUE TITLE
Bai og C2b - "Nei" skal ikke være med ut i kriteriefremstillingen

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#331]
Valgene "Nei" for disse to underkriteriene skal ikke vises i kategorifremstillingen.
related to #322

**Comment by KristineLund** [comment]
mulig dere er klar over det, men det er fortsatt noe bøgg i Bai/Ba(i). Her skal kun Ba(i) Trolig kraftig fragmentering være gjeldende 
![image](https://user-images.githubusercontent.com/25904198/140912009-3537b67d-1281-40d5-9a7f-62e645e85929.png)

**Comment by SiriKasperdatter** [comment]
Enda? :/ er fiksen fra #369 merget @matssa?

**Comment by helemork** [comment]
den ble merget... nettopp så skal være i orden nå. 
MEN jeg jobber uansett med kriterievisningen nå, så når det er på plass trengs nok en ekstra gjennomlesning uansett
