### ISSUE TITLE
Slette gammelt repo (assessments-api)

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#344]
den gamle backendløsningen kan slettes 
(jeg har ikke tilgangen):
https://github.com/Artsdatabanken/assessments-api/settings

usikker om kanskje det også er andre ting som kan slettes i forhold til docker/devops andre plasser også?

**Comment by helemork** [comment]
Det står du er admin og skal ha tilgang :)
Er det nok å arkivere, eller vil vi slette fullstendig?

**Comment by eirikn-artsdatabanken** [comment]
har allerede arkivert, kan slettes permanent

![image](https://user-images.githubusercontent.com/69149042/139841287-324e66a6-dad8-4a6e-8ed9-d7e4e73aebea.png)

**Comment by helemork** [comment]
Så rart, det sto jo du skulle hatt full tilgang.
Jeg har nå slettet det.
