### ISSUE TITLE
Rangindikatorer

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#354]
Vi må ha med rangindikatorer for taksoner under artsnivået. 
Det er vitenskapelignavnID dere henter ut info fra? I så fall må vi ha med **subsp./var./f.** for de taksa det gjelder, og den infoen kan vel hentes ut via vitenskapelignavnID, forhåpentligvis?

**Comment by SiriKasperdatter** [comment]
Også håper jeg egentlig at vi ikke har noen quadrinomen, men det må vi kanskje spørre om assistanse fra @steinho for å finne ut av det?

**Comment by SiriKasperdatter** [comment]
- [ ] n.sp. /sp. (ting som ikke er navn) skal ikke ha kursiv. 
Gjelder: _Zelotes_ n. sp., _Nebalia_ sp. og _Passaloecus_ n. sp.
Tror ikke vi har flere slike i basen (håper jeg).

**Comment by steinho** [comment]
Moi fiks - TaxonRank vil snart inneholde variety og form i tillegg til subspecies og species - slik at man kan sette inn riktig tekst i navnet...

**Comment by steinho** [comment]
![image](https://user-images.githubusercontent.com/3253353/140873464-eb2e9822-4f92-46d4-a1be-23974b725943.png)
