### ISSUE TITLE
Utbredelse - tekstendring

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#38]
For artsgruppen pattedyr (Svalbard) burde utbredelse-teksten endres til:

Vurderingen gjelder for Svalbard, dvs. Spitsbergen og øyene omkring, samt Bjørnøya og Hopen inklusiv kyst innen 12 nautiske mil. Arten har vært gjennom full rødlistevurdering.

"Arten har vært gjennom full rødlistevurdering" har vel en if/else-spørring dersom kategori er LC eller en av rødlistekategoriene?

**Comment by helemork** [comment]
Bare så jeg er helt sikker på at det blir riktig: 
@SiriKasperdatter Per nå er det ingen skilnad mellom svalbard generelt og svalbard for pattedyr i tekstene. Ønsker du jeg skal legge til en sjekk for dette tilfellet og beholde eksisterende tekst for resten, eller bytte ut for alle svalbard?

Og ja, det er omtrent 20 forskjellige if-setningermed forskjellig tekst. Vi kan kanskje ta en gjennomgang sammen på dem en dag?

**Comment by SiriKasperdatter** [comment]
Nå tenker jeg altså bare på avsnittet om "Utbredelse", der er det forskjell. 
Isbjørn: 
![image](https://user-images.githubusercontent.com/61016662/124563585-752ba580-de40-11eb-8304-58a2a8282b63.png)
Brunbjørn: 
![image](https://user-images.githubusercontent.com/61016662/124563639-82489480-de40-11eb-935a-8b6eceb67682.png)

Ønsker å endre innlagt tekst for samtlige vurderinger i artsgruppen pattedyr (Svalbard). 

Ja, det kan vi godt. Kanskje vi kunne fått se en oversikt over alle?

**Comment by KristineLund** [comment]
Blir også gjerne med på et møte om If-setninger

**Comment by helemork** [comment]
Supert.
Inntil videre ligger det jeg kopierte over fra innsynet (det som genereres i "Informasjons"- blokka øverst) her: https://github.com/Artsdatabanken/assessments-frontend/blob/master/Assessments.Frontend.Web/Views/Test/partials_2021/_Informasjon.cshtml og er omtrent ikke rørt fra innsynsløsningen.
