### ISSUE TITLE
Småplukk

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#388]
- [x] Fjern semikolon fra avsnittet om Vurderingsområde og artens utbredelse
![image](https://user-images.githubusercontent.com/61016662/141481743-9516b99a-4404-4ca9-8364-b2c3a5aef9b5.png)

- [x] Avsnitt om Årsak til endring av kategori mangler punktum
![image](https://user-images.githubusercontent.com/61016662/141481869-1f9c3d84-82c6-49e8-9317-4b76380a95b5.png)

- [x] I full liste ser det ut som B-kriteriet er gjeldende selv om det ikke er det, eksempel: https://assessments-fe.test.artsdatabanken.no/rodlisteforarter/2021/1727

- [x] Legg på lenkefargegreie på pila også, for uproffe brukere :) 
![image](https://user-images.githubusercontent.com/61016662/141482097-af5eac27-b8a5-440a-a79f-b6963c0a093a.png)

- [x] Mangler en d på https://assessments-fe.test.artsdatabanken.no/rodlisteforarter 
![image](https://user-images.githubusercontent.com/61016662/141737172-9c9c8eb9-8066-44fd-9258-efd22f4c9dea.png)

-  #396

- [x] Liten n i november øverst på vurderingssidene
![image](https://user-images.githubusercontent.com/61016662/141794268-79ce54fd-9aca-41b8-be5b-2a0e6149688f.png)

- [x] Fjern den taksonomiske stien for alle vurderinger
![image](https://user-images.githubusercontent.com/61016662/141947199-9090e405-f102-40b3-b264-d92c0016fb9d.png)

- [x]  Oppsummering med to m-er
![image](https://user-images.githubusercontent.com/61016662/141956330-2e8596a3-9389-4fb9-99e3-adc66760f689.png)

**Comment by KristineLund** [comment]
- [ ] Feil i Konklusjon for B-kriteriet på vurderinga 13021 (underkriterier b og c på B). (Det står "B-kriteriet er ikke gjeldende" når det definitivt er det)
