### ISSUE TITLE
Tekst om dørstokkart

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#39]
@KristineLund: 

Overordnet informasjon (2/3): lenken i "Arten er fremmed, og ble enten etablert innenfor gjeldende område etter år 1800 eller antas å kunne etablere seg innen 50 år (dørstokkart). les mer" hører til "dørstokkart"-begrepet. Kanskje flytt lenken inn i "(dørstokkart - les mer)" evt. fjerne lenken?

**Comment by helemork** [comment]
Her trenger jeg nok hjelp til å finne en eksempel-art slik at det blir litt lettere å finne ut hva som skal endres.

**Comment by KristineLund** [comment]
For eksempel: https://assessments-fe.test.artsdatabanken.no/test/21156?year=2021 
Den ser sånn ut på innsynet: https://innsyn.test.artsdatabanken.no/artsrapport/tilbakemelding/21156

**Comment by helemork** [comment]
Per nå ser det jo likt ut, har jeg rett i at du har korrigert den?

**Comment by KristineLund** [comment]
Ja, jeg la inn lenken i "(dørstokkart)", men jeg fant ikke igjen hvor "les mer" var i koden, så jeg fikk ikke fjernet den gamle lenken. "Les mer" er altså erstattet nå og kan gjerne tas bort :)

**Comment by KristineLund** [comment]
Denne issuen kan lukkes så snart "les mer"-lenka er tatt bort. 
![image](https://user-images.githubusercontent.com/25904198/129148937-ac2462eb-9a90-4d97-9b9c-d74842594a66.png)
