### ISSUE TITLE
sjekk av statistikkvisning

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#400]
etter oppdatering fra basen man 15.11. Utvalg: "Norge", "truede arter", "arter"

- [x] antall per kategori -_OK_
- [x] antall per kriterie -_OK_
- [x] antall per habitat -_OK_
- [x] antall per region -_OK_
- [x] antall per påvirkningsfaktor -_diff +/- 1 på forurensning, fremmede arter_

**Comment by KristineLund** [comment]
@matssa den lille differansen på påvirkningsfaktorer skyldes mest trolig at jeg fjerner faktorer hvor omfang="". Det finnes noen sånne, og de er nok ganske gamle. Vi kan diskutere om de evt. skal telles med @SnorresKongesaga

**Comment by SnorresKongesaga** [comment]
Hvis vi antar at de har angitt relevant påvirkningsfaktorer så kan vi tolke manglende verdi som "ukjent" omfang @KristineLund

**Comment by helemork** [comment]
Ser ut som denne issuen er ferdig, kan den lukkes?

**Comment by KristineLund** [comment]
løsningen ble å manuelt endre "" i basen til ukjent - done
