### ISSUE TITLE
Autogenerert tekst på RE-arter burde være i fortidsform

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#41]
@KristineLund : Overordnet informasjon (3/3): Ikke-utdødde rødlistearter høres utdødde ut :) "Arten er dokumentert eller antatt å ha vært etablert med fast reproduserende bestand og hadde ikke opphav i introduserte individer." - tror nok denne hørte til RE-knaggen.

Teksten tilhører "etablertBestandINorge" som dukker opp i mange ifsetninger som burde tatt en gjennomgang. Om den opptrer på feil sted er det fint å få luket ut. Fila er direkte kopi fra innsynet, og trenger nok en liten kontroll for å sikre at alt er korrekt.

**Comment by KristineLund** [comment]
Endret tekst i glossary.json så nå omtales alle arter i nåtid. Men arter under RE-knaggen (utdoddINorgeRE) burde nok omtales i fortid for at det skal gi mening for leseren?

etablertBestandINorge, etablertFør1800 og ikkeReproduserendeINorge er options på både UtdoddINorgeRE, RodlisteVurdertArt og tilsynelatende (i basen) også på sikkerBestandLC, men har altså litt ulik betydning for RE vs. rødlistevurdert/LC.

**Comment by KristineLund** [comment]
Dagens tekst f.eks. på en RE-art som har vært etablert før den døde ut: "Det er svært liten tvil om at arten er utdødd fra Norge (RE). Arten **er** dokumentert eller antatt etablert med fast reproduserende bestand og **har** ikke opphav i introduserte individer." - Nåtidsform høres litt rart ut når arten er gone

**Comment by helemork** [comment]
Enig. Hva vil du jeg skal gjøre?
Men når vi først er på den setningen - den er litt tung. Jeg måtte lese den to ganger for å forstå at den mener at arten er tidligere kjent i norge og ikke en introdusert art. Dette gjelder mange av tekstene, men vi kan ta en gjennomgang litt senere når det strukturelle er mer på plass

**Comment by KristineLund** [comment]
Har skrevet om rodlisteVurdertArt-options så de også fungerer i fortidsform
