### ISSUE TITLE
Mangler 2015-kategori

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#411]
Følgende arter mangler 2015 på frontend https://assessments-fe.test.artsdatabanken.no/ 

Cortinarius conterminus
Cortinarius salicticolus
Theridiosoma gemmosum
Xylota caeruleiventris

Se vedlegg for mer info (ID etc)

Se prduksjonsbasen eller https://rl2021api.artsdatabanken.no/api/ExpertGroupAssessments/export/absoluteall for fasit

[Mangler 2015 kategori.xlsx](https://github.com/Artsdatabanken/assessments-frontend/files/7554913/Mangler.2015.kategori.xlsx)

**Comment by SnorresKongesaga** [comment]
Lenke til 2015-vurderingen mangler for Theridiosoma gemmosum

Xylota caeruleiventris mangler lenke til 2015 og 2010

**Comment by steinho** [comment]
> Lenke til 2015-vurderingen mangler for Theridiosoma gemmosum
> 
> Xylota caeruleiventris mangler lenke til 2015 og 2010

Jeg fant i farten ikke visning av dem i resultatene for 2015 - url - kun kategori i basen ... men skal sjekke en gang til....

**Comment by steinho** [comment]
> > Lenke til 2015-vurderingen mangler for Theridiosoma gemmosum
> > Xylota caeruleiventris mangler lenke til 2015 og 2010
> 
> Jeg fant i farten ikke visning av dem i resultatene for 2015 - url - kun kategori i basen ... men skal sjekke en gang til....

Da fant jeg alle unntatt: Cortinarius conterminus

**Comment by steinho** [comment]
kommer plutselig ut

**Comment by steinho** [comment]
kom ut!
