### ISSUE TITLE
Statistikkvisning 

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#42]
**Hoved-issue for statistikkvisning**
Utkast til figurer i statistikkvisning og mer utfyllende info [her](https://artsdatabankenno-my.sharepoint.com/:p:/g/personal/kristine_bjornaas_artsdatabanken_no/EadEcQ3dxqFBv3kEhfCE9FgBKv7BXx90J0iDpW1BBdcxZw?e=6mYEz2) 

Legge ferdig utregnet data for statistikk som skal vises på listesiden - #42

- [x] (1) Antall per kategori (obs. kategorier med gradetegn VUº = VU for dette formålet), men ekskluder kategori NA og NE i figuren (utvalg i utvalget).

**for de resterende gir det kun mening å ta med trua og nær trua arter, dvs. kategoriene NT, VU, EN og CR  (utvalg i utvalget)**

- [x] (2) Antall per gjeldende kriterie (A, B, C, D, E). _Edit: muligens utdatert: I eksporten fra Rødlistebasen ligger gjeldende kriterier i kolonna "Kriterier2021" som en tekststreng (antar jeg), eks. "A2(c)+3(c)+4(c); B2a((i))b(ii,iii,iv); C1+2a(i)" - her er A, B og C alle gjeldende hovedkriterier, dvs. hovedkriteriet er det eneste m stor bokstav. (PS1: Siden en art kan ha flere gjeldende kriterier blir ikke totalsummen lik antall CR, EN, VU og NT- arter, men det er ok, PS2: en vurdering kan ha flere kriterier helt eller delvis utfylt, men alle er ikke nødvendigvis utslagsgivende for kategori, derav utheving. Men om du går etter "Kriterier2021" blir det riktig.)_

- [x] (3) Antall per hovedhabitat. En vurdering/art kan ha flere hovedhabitat, så summen blir større enn totalen av vurderinger.

- [x] (4) Antall per hovedkategori av påvirkningsfaktorer (høyeste nivå av påvirkningsfaktor-stien, eks. "Påvirkning på habitat"). Edit: kun på overordnet nivå. _OBS: Selv om det finnes flere former av eks. "Påvirkning på habitat" på en vurdering, bør den telles én gang per vurdering._

- [x] (5) Antall per region/havområde med "kjent" forekomst.

**Comment by helemork** [comment]
- I grafen vi har nå for region tok jeg med kjent og antatt kjent forekomst for region.
Dette fordi etter å ha sett på mange av vurderingene virker det som ekspertene ofte bruker de to statusene sammen på samme vurdering, men hvorav noen har litt mer usikkerhet. Dette kan endres med noen få tastetrykk ved behov.

- Nå er ikke regioner satt på LC arter filtrert vekk. Dette burde egentlig ikke være nødvendig, da de egentlig burde vært strippet vekk på et tidligere tidspunkt? Eller hva kom vi frem til der?

- Påvirkningsfaktor statistikk må vente til etter #32 er i mål

- Kriterier ble riktig når jeg fjernet forsøkene på filtrering. Jeg vet ikke hvorfor de skapte trøbbel, men uten dem ble det identisk med test-eksempelet fra eksporten.

**Comment by KristineLund** [comment]
For graf 2-5 gir det mening å strippe bort RE, LC, NA, DD og NE, ja (se første innlegg). Helst kun "kjent" forekomst på region.

**Comment by KristineLund** [comment]
@KristineLund ser på "bildetekster" i statistikkvisningen

**Comment by helemork** [comment]
@matssa kan få i oppdrag å hente ut tall til graf for påvirkningsfaktorer. Utelukkende øverste nivå.
