### ISSUE TITLE
Svalbard - Hvorfor er denne arten vurdert?

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#423]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/61016662/142412651-17c652fa-4880-4a32-9279-6d92c6879265.png">

Endre fra "Norge" til "Svalbard" for Svalbardvurderingene

**Comment by helemork** [comment]
Jeg bytter om til vurderingsområdet i glossary på denne, da det er flere av disse som matches i forskjellige rekkefølger, og det er en del ekstra logikk som blir litt overflødig for å bytte navnene her. I noen står teksten like godt uten. Det har vi gjort på andre ting tidligere, så det passer inn med resten av tekstene.
