### ISSUE TITLE
Endre "Rødlistekategori" innledningsvis

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#43]
![image](https://user-images.githubusercontent.com/61016662/124708065-fc891f80-def9-11eb-8ed0-d0c1c7d82361.png)

Endre "Rødlistekategori" til "Kategori Rødlista 2021"

I tillegg bør forkortelsen stå sist og definisjonen stå i kursiv (gjelder samtlige kategorier), slik som i innsynet: 
![image](https://user-images.githubusercontent.com/61016662/124708339-70c3c300-defa-11eb-8b67-dd771de70bc4.png)

**Comment by helemork** [comment]
Endringen er allerede på vei :) 
Men Rødlista med stor R denne gangen?

**Comment by SiriKasperdatter** [comment]
Ja, for her trenger det ikke stå "Norsk" først :) 
Norsk rødliste for arter 
Rødlista for arter
