### ISSUE TITLE
Legg til % på C2a(ii)

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#432]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/61016662/142492335-4895ba60-d396-43f7-844d-03529a22c4d6.png">
Legg til % etter terskelverdiene 100, 95 og 90. Ser unit er satt, men blir ikke med ut?

**Comment by helemork** [comment]
Denne er satt opp som... et unntak, mest sannsynlig fordi vi ikke ville ha prosent med der det var noe annet i teksten... som igjen ble feil på disse.
Antar vi burde hatt snevrere unntak slik som på de vi fiksa i går.
