### ISSUE TITLE
Gradtegn mangler på vurderingen

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#435]
Inne på vurderingen så mangler gradtegnet i "kategoriskalaen". Det må være med!

**Comment by SiriKasperdatter** [comment]
Ser også at de nedgraderte "mister" fargen sin i søket
<img width="426" alt="image" src="https://user-images.githubusercontent.com/61016662/142599920-e27b3bf8-9ffd-4787-aa3d-2e881d661721.png">
