### ISSUE TITLE
Statistikk - småplukk

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#436]
- [x] Tusentallsskilletegn når > 5 siffer PRI 2
<img width="451" alt="image" src="https://user-images.githubusercontent.com/61016662/142598913-fb426fe5-6b2f-4427-b0d6-8d073a891034.png">

- [x] Endre "per kriterie" til "per kriterium" PRI 1
<img width="183" alt="image" src="https://user-images.githubusercontent.com/61016662/142599011-67f50927-b3d6-4d23-a221-6dadcb67bbfc.png">

- [x] Antall vurdering per habitat - endre "habitat" til "habitattype" PRI 2
<img width="181" alt="image" src="https://user-images.githubusercontent.com/61016662/142599147-f0746d91-30dc-4276-a788-c83345ce6a5b.png">

- [ ] Sidetellingen, skal den være med når man har trykket på statistikk..? DISKUSJON?
<img width="398" alt="image" src="https://user-images.githubusercontent.com/61016662/142599287-df60e3bc-eaa4-436a-b3d9-c8cd69e8cb38.png">

- [x] Liten n i november på "landingssiden" også PRI 1
<img width="332" alt="image" src="https://user-images.githubusercontent.com/61016662/142602867-856c94d0-385b-438b-9f50-f68689238507.png">

**Comment by matssa** [comment]
Sidetellingen bør ikke være med når man ser på statistikk. Lagde ny issue på den: https://github.com/Artsdatabanken/assessments-frontend/issues/438
