### ISSUE TITLE
Bruk av begrepet "art" når vi også støtter bla. varietet

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#44]
@KristineLund  skrev: Ingress (3/3): det kan være litt forvirrende at det står "Arten" når det ikke bare er arter som er vurdert, f.eks. kan det være litt vanskelig å finne fram til at dette er en varietet: https://assessments-fe.test.artsdatabanken.no/test/37835?year=2021. Forslag til løsning: ... 

--
Dette føler jeg kan være en debatt å ta, og at ved en avgjørelse bør potensielt alle instanser av ordet art byttes ut med korrekt term. Da må alle tekstes sjekkes over.

**Comment by SnorresKongesaga** [comment]
Er det tekst som kommer fra oss, f.eks. "Hovedhabitater arten finnes i" du tenker på? Å så fall er jeg selvsagt enig i at det hadde vært fint om det sto rett taksonomisk nivå. 

Hvis det er overkommerlig kan du sette det som pri 3

**Comment by KristineLund** [comment]
Satt som pri2 etter møtet 9. nov. nå som Stein har hentet ut varietet/underart/form. Vi bør endre fra "Arten" til "Underarten"/"Varieteten"/... i 
- [ ] Ingressen (viktigst!)
- [ ] Under og i tittelen på Forklaring på kategori > Hvorfor er denne arten vurdert?
- [ ] I tittelen på Hvilke kriterier gjør at denne arten er rødlistet? - endre gjerne til det mer generelle "En art"... i teksten under
- [ ] under Påvirkningsfaktorer
- [ ] Under habitat kan det endres til "En arts habitat er dens..." - det bør være greit med "en art", for da oppfattes det mer generelt. 
- [ ] under Generasjonstid

**Comment by helemork** [comment]
Denne er fikset
