### ISSUE TITLE
Det henger med ekstra tekst under "Utvikling"

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#440]
Det er noe ekstra rusk i kategorinavnet, eks. her hos Pavelius smiley 35980
<img width="220" alt="image" src="https://user-images.githubusercontent.com/25904198/142830593-24c54042-973a-4e3a-855a-d410355422f7.png">

**Comment by KristineLund** [comment]
Den er vurdert for første gang i 2021... er det det som står der kanskje?

**Comment by helemork** [comment]
Ahh, ja.
Den teksten er ikke så nyttig egentlig, kanskje den bare skal fjernes?

**Comment by KristineLund** [comment]
Det er nok like greit, ja
