### ISSUE TITLE
Bildelisenser 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#446]
En liten (i) knapp med fotograf, lisens og hvor det er fra hadde uansett vært god praksis. 
Sannsynligvis også påkrevd etter enkelte av lisensene. Så det må på plass, men etter lansering.

**Comment by matssa** [comment]
Vi har med lisens på de plassene vi har bilde. Kun fremmedartslista har bilder enn så lenge.
