### ISSUE TITLE
Taksonomisk sti? Kjør debatt.

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#45]
Det er uttrykt ønske om en taksonomisk sti, men det er også uttrykt skepsis mot en taksonomisk sti/hierarki. Kan vi finne en løsning alle er enige om?

**Comment by SnorresKongesaga** [comment]
Taksonomisk sti må vi ha. Kun vitenskapelig navn og ekspertkomite/artsgruppe vil i mange tilfeller ikke tilstrekkelig informasjon.

**Comment by helemork** [comment]
denne har en egen issue senere og kan ansees som duplikat.
