### ISSUE TITLE
Default-valg

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#471]
Vi bør virkelig vurdere å sette Norge som default i filteret igjen. 
Kan godt diskutere om vi bør gjøre det samme med taksonomisk nivå - art. 
Ser det er litt rot med tall og utvalg ute og går.

**Comment by helemork** [comment]
Vi har det i selve applikasjonen, men spørs om routingen til @steinho ikke tar med noen parametere.

Forøvrig må det sies at å gjøre valg for en bruker ofte kan være forvirrende, spesielt på mobil der det ikke er så synlig.  Hvis vi får på plass at hvert filter har sin egen sånn chip der oppe, sånn som vi har diskutert litt, så er vi på god vei :)

**Comment by steinho** [comment]
Endre url på redirect?

**Comment by helemork** [comment]
Ja, internt i løsningen legger vi på ?Area=N når man kommer dit uten noe. 

Det har positive og negative sider. For brukere som er spesielt interressert i svalbard, men ikke ser så godt er det veldig uheldig - da de ikke nødvendigvis ser filteret med en gang. For brukere som er folk flest derimot er det nå 2X enkelte dyr som vil si at tallene de bruker i some og media fort kan bli litt feil.... siden de teller dyra på svalbard og norge to ganger.

Mao: Bør diskuteres litteranne. Om vi får tydeliggjort bedre at det allerede er valgt "Norge" og "art" i filteroppsummeringen er jeg veldig for det.

**Comment by helemork** [comment]
Vi bestemte å ikke ha default valg.
