### ISSUE TITLE
Forfatterrekkefølge - lav

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#484]
Nederst her: https://artsdatabanken.no/lister/rodlisteforarter/2021/13579

 er det følgende rekkefølge: "Haugan R, Timdal E, Ihlen PG, Holien H og Hovind AA." Dette skal stå alfabetisk, dvs Haugan, Holien, Hovind, Ihlen og Timdal.

**Comment by helemork** [comment]
Vil det si at for ekspertgruppene er førsteforfatter alltid alfabetisk bestemt, og ikke basert på hvem som har hatt gruppelederansvar? Jeg trodde noen av gruppene hadde det. Har fiksa i en grein som ikke er merget inn ennå.

**Comment by SnorresKongesaga** [comment]
Alltid komitéleder først. Reidar Haugan er komiteleder, og kommer tilfeldigvis også først alfabetisk

**Comment by helemork** [comment]
Ok, men hvordan vet jeg hvem som er komiteleder? nå satte jeg jo på alfbetisk sortering...

**Comment by eirikn-artsdatabanken** [comment]
man kan sikkert bruke noe slikt for å sortere på leder først:

`.OrderBy(x => new List<string> { "Leder "}.IndexOf(x.Role)).ThenBy(x => x.LastName)`

**Comment by eirikn-artsdatabanken** [comment]
kanskje bruke 

`.OrderBy(x => new List<string> { "Leder", "Medlem"}.IndexOf(x.Role)).ThenBy(x => x.LastName)`
