### ISSUE TITLE
Oppdaterte vurderinger etter lansering - hvordan merke?

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#492]
Det har blitt oppdaget noen feil som gjør at enkelte vurderinger må oppdateres. Her bør vi vel sette på en merkelapp om at vurderingen er oppdatert, noe ala som ble gjort for Fremmedartslista 2018. Tar gjerne en diskusjon på hva som er beste løsning her.

**Comment by helemork** [comment]
absolutt. dette skal vi få til. ta på oppsummeringsmøtet eller allerede nå?

**Comment by SiriKasperdatter** [comment]
Kanskje et eget møte? Ser for meg tida går på oppsummeringsmøtet,  og dette trenger vel ikke alle å være med på. Ikke brennhast, men helst i løpet av uka iallfall.

**Comment by helemork** [comment]
Todo @steinho : databasemodellendring. 
- Timestamp for sist endring
- endringstype: skrivefeil eller meningsendring
- tekstfelt som beskriver endring utført som fylles inn av personen som oppdaterer.

Forslag:
- Under ekspertkomitenavn og publisert, legg til oppdatert timestamp + "Endret [dato] - korrigert skrivefeil" eller "Endret [dato] - meningsendring" (kom gjerne med bedre formuleringer her altså)
- Hvis det er meningsendring, legg inn endringsteksten i slutten av ingressen. Enten rett inn eller som nytt avsnitt? 
- Oppdater siteringsfelt. Det er ingen grunn til å vise gammel måte å sitere på. Ettersom man nå skal sitere på nyeste versjon er det forvirrende at det står to varianter der. Det bør jo kun være dato som er endret.

**Comment by SiriKasperdatter** [comment]
Det er satt frist til i morgen for beskjed om endringer. Deretter kan det kjøres reindex fra vår side når de tekniske løsningene er på plass. Jeg har liste over endringene og kategoriserer dem med tanke på formuleringer som skal fremvises på sidene.

**Comment by steinho** [comment]
@SiriKasperdatter - har du den 15 vurderingene som er endret - trenger en liste med helst ID'er og navn på art. Vil da finne de som er publisert - før dere begynte å redigere inn det som skal endres - altså de som var gjeldende pr 24 nov....

**Comment by SiriKasperdatter** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/shl/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/shl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72" lang=NO-BOK style='tab-interval:35.4pt;
word-wrap:break-word'>



ID | Takson
-- | --
238 | Combocerus glaber
25442 | Allium ursinum
30664 | Lysiella oligantha
18942 | Arabis hirsuta var. glaberrima
34822 | Dactylorhiza incarnata subsp. lobelii
1979 | Monotropa hypopitys subsp. hypopitys
3777 | Diphasiastrum ×zeilleri
6135 | Thalictrum simplex
2714 | Thalictrum simplex subsp. simplex
10509 | Logfia minima
29142 | Potamogeton friesii
26124 | Carex punctata
8323 | Phleum pratense subsp. nodosum
37848 | Callitriche platycarpa



</body>

</html>

**Comment by steinho** [comment]
> <style> </style>
> ID	Takson
> 238	Combocerus glaber
> 25442	Allium ursinum
> 30664	Lysiella oligantha
> 18942	Arabis hirsuta var. glaberrima
> 34822	Dactylorhiza incarnata subsp. lobelii
> 1979	Monotropa hypopitys subsp. hypopitys
> 3777	Diphasiastrum ×zeilleri
> 6135	Thalictrum simplex
> 2714	Thalictrum simplex subsp. simplex
> 10509	Logfia minima
> 29142	Potamogeton friesii
> 26124	Carex punctata
> 8323	Phleum pratense subsp. nodosum
> 37848	Callitriche platycarpa

Spørringen under la inn 14 revisjoner med den datoen som var nærmest opp imot lansering

INSERT INTO AssessmentRevisions
                         (Id,[RevisionId]
      ,[RevisionDateTime]
      ,[FutureRevisionDateTime]
      ,[AssessmentHistoryId]
      ,[AssessmentHistoryHistoryAt])
SELECT        Id, 1 AS Expr1, '2021.11.24' AS Expr2, '2021.12.14' AS Expr3, Id AS Expr4, MAX(HistoryAt) AS Expr5
FROM            AssessmentHistories
WHERE        (HistoryAt < '2021.11.25') AND (Id IN (238, 25442, 30664, 18942, 34822, 1979, 3777, 6135, 2714, 10509, 29142, 26124, 8323, 37848))
GROUP BY Id

**Comment by SiriKasperdatter** [comment]
Da er det innlagt begrunnelse for vurderingene, @helemork. 

_NB - Vurderingen er justert etter publisering:_
_<Hva som er endret [hentet fra endringsfeltet i RLB]>_

**Comment by SiriKasperdatter** [comment]
Da har det kommet endringer på to til. Har gjort endringene og lagt inn begrunnelse i endringsloggen. 
Gjelder: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/shl/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/shl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



23974 | Andrena hattorfiana
-- | --
337 | Andrena marginata



</body>

</html>

**Comment by steinho** [comment]
Alt her skal være på plass - så langt jeg kan se

**Comment by SnorresKongesaga** [comment]
To nye arter som må oppdateres @steinho . Jeg la inn endiring i basen 12.01.22

6225	Melangyna ericarum 
27783	Eumerus flavitarsis

**Comment by SiriKasperdatter** [comment]
To til som må oppdateres @steinho. Innlagt i produksjonsbasen 21.01.22

34749 Hygrocybe hygrocyboides
1611 Harmajaea harperi

**Comment by SnorresKongesaga** [comment]
Her kommen en ny endring (elfenbenslav) @steinho . Andel av europeisk bestand oppdatert:

31892 Heterodermia speciosa

**Comment by SnorresKongesaga** [comment]
Har endret gjeldene kriterium på 1725 Geastrum schmidelii, dvergjordstjerne (SOPP). Fjernet kriterium B1. Arten går fra CR til EN. @steinho kan du høste?

**Comment by steinho** [comment]
> Har endret gjeldene kriterium på 1725 Geastrum schmidelii, dvergjordstjerne (SOPP). Fjernet kriterium B1. Arten går fra CR til EN. @steinho kan du høste?

har lagt til revisjon - såg ut som den før lansering var den forrige - derav dato HistoryAt < '2021.11.25:
INSERT INTO AssessmentRevisions
                         (Id,[RevisionId]
      ,[RevisionDateTime]
      ,[FutureRevisionDateTime]
      ,[AssessmentHistoryId]
      ,[AssessmentHistoryHistoryAt])
SELECT        Id, 1 AS Expr1, '2021.11.24' AS Expr2, '2022.03.21' AS Expr3, Id AS Expr4, MAX(HistoryAt) AS Expr5
FROM            AssessmentHistories
WHERE        (HistoryAt < '2021.11.25') AND (Id IN (1725))
GROUP BY Id

**Comment by steinho** [comment]
@SnorresKongesaga https://www.artsdatabanken.no/lister/rodlisteforarter/2021/1725

**Comment by SnorresKongesaga** [comment]
Har fjernet avhaking"Trolig utdødd". Publiseres IKKE som ny versjon. Gjelder føø

4260	Acmaeops smaragdulus		Biller
437	        Ceutorhynchus chalybaeus		Biller
3391	Dermestes laniarius		Biller
1420	Diplapion stolidum		Biller
29496	Fissidens crassipes	elvelommemose	Moser
30236	Nomada argentata	bakkevepsebie	Vepser
449	        Octotemnus mandibularis		Biller
17187	Peniophorella echinocystis	elverovskinn	Sopper
5138	Temnostoma angustistriatum	smal treblomsterflue	Tovinger

**Comment by SnorresKongesaga** [comment]
Har rettet feil populærnavn i teksten Publiseres IKKE som ny versjon. Gjelder følgende art @steinho 
1979 Monotropa hypopitys subsp. hypopitys Karplanter

**Comment by steinho** [comment]
> Har rettet feil populærnavn i teksten Publiseres IKKE som ny versjon. Gjelder følgende art @steinho 1979 Monotropa hypopitys subsp. hypopitys Karplanter

Teoretisk på plass - kunne du sjekket

**Comment by eirikn-artsdatabanken** [comment]
@SnorresKongesaga publisert på nytt nå

**Comment by SnorresKongesaga** [comment]
Har fjernet tekst og påvirkningsfaktor (gammelt grums fra 2018): Hypera postica, lusernegnager
https://artsdatabanken.no/lister/rodlisteforarter/2021/10159
Publuseres IKKE som ny versjon @eirikn-artsdatabanken

**Comment by SnorresKongesaga** [comment]
Rettet "skrivefeil" på lomvi Uria aalge (Svalbard): https://artsdatabanken.no/lister/rodlisteforarter/2021/31883
Publuseres IKKE som ny versjon @eirikn-artsdatabanken

**Comment by SnorresKongesaga** [comment]
Rettet skrivefeil på tindved Hippophaë rhamnoides (Karplanter Norge), https://artsdatabanken.no/lister/rodlisteforarter/2021/21760
Publuseres IKKE som ny versjon @eirikn-artsdatabanken

**Comment by eirikn-artsdatabanken** [comment]
har laget nye filer lokalt, og testet litt - men ser ingen endringer i datakilden på de to siste vurderingene du nevner her ([31883](https://artsdatabanken.no/lister/rodlisteforarter/2021/31883) og [21760](https://artsdatabanken.no/lister/rodlisteforarter/2021/21760))

@SnorresKongesaga kan du skrive nøyaktig hva som er endret så kan jeg prøve å finne ut hvorfor man ikke ser det i filene som blir produsert?

**Comment by SnorresKongesaga** [comment]
Det er veldig små endringer

31883	Skrivefeil i teksten (forglemmelse). Har endret fra "sårbar" til "nær truet"
21760	Endret setningen: "Arten kan rotskudd, og noe formering skjer langs vassdrag med løsrevne røtter" til "Arten har rotskudd, og noe vegetativ formering skjer derfor med løsrevne røtter langs vassdrag"

Jeg kommer ikke på å mase på deg for å legge ut ny versjon hvis det bare er rene skrivefeil, men siden vi må oppdatere 31883 (ganske alvorlig feil) så benyttet jeg anledningen til å fikse 21760 også
 @eirikn-artsdatabanken

**Comment by eirikn-artsdatabanken** [comment]
det er greit å legge ut nytt for min del, jeg klarte bare ikke se endringene når jeg testet - fant ut hvorfor og har publisert nye filer nå

er kjekt å vite hva man skal sjekke ved endringer 👍

**Comment by SnorresKongesaga** [comment]
Helt enig. Derfor skriver jeg inn endringene i feltet "kommentarer til intern bruk" i Rødlistebasen. Jeg kan være enda mer presis om ønskelig. Jeg har også en oversikt hvor jeg beskriver endringene. Ligger her: "T:\alle\P_Rødliste\2021\Endringslogg etter lansering\Endringer etter lansering_instruksNettside.xlsx"

**Comment by SnorresKongesaga** [comment]
40194	Acipenser oxyrinchus	atlanterhavstør	Fisker	Den hadde ingen kategor. Satte den til NA slik at vi ikke trenger å sette den til NR på FA-lista

**Comment by SnorresKongesaga** [comment]
@eirikn-artsdatabanken Mange endringer. Full oversikt her "T:\alle\P_Rødliste\2021\Endringslogg etter lansering\Endringer etter lansering_instruksNettside.xlsx

gjelder:

**ID	        Takson**
33233	Polydora cornuta
33284	Pseudopolydora paucibranchiata
	        Pseudopolydora nordica Radashevsky, 2021
3634	Argyresthia fundella
6409	Argyresthia trifasciata
30357	Epinotia fraternana
15960	Sitophilus granarius
12580	Encarsia formosa
11926	Anthocomus equestris
34792	Anteon scapulare

**Comment by steinho** [comment]
> 

Er dette endringer som skal føre til at de blir markert som ny revisjon(ny versjon?)

**Comment by SnorresKongesaga** [comment]
Ja

**Comment by steinho** [comment]
> Ja

Har fixet revisjoner for alle unntatt den nye - den har jo ikke fysisk tidligere revisjon... Jeg kjører transformering straks.

Ble litt ballus med tre av dem da de ikke hadde historikk - hadde aldri vært redigert i 2021 basen - etter import fra 2015 basen, Men tror jeg fikk til ok revisjon 1 der.

```sql
INSERT INTO AssessmentRevisions
                         (Id,[RevisionId]
      ,[RevisionDateTime]
      ,[FutureRevisionDateTime]
      ,[AssessmentHistoryId]
      ,[AssessmentHistoryHistoryAt])
SELECT        Id, 1 AS Expr1, '2021.11.24' AS Expr2, '2022.12.19' AS Expr3, Id AS Expr4, MAX(HistoryAt) AS Expr5
FROM            AssessmentHistories
WHERE        (HistoryAt < '2021.11.25') AND (Id IN (33233, 33284, 3634, 6409, 30357, 34792))
GROUP BY Id

-- disse hadde ikke vært lagret før lansering i 2021 basen - kun importert
INSERT INTO AssessmentRevisions
                         (Id,[RevisionId]
      ,[RevisionDateTime]
      ,[FutureRevisionDateTime]
      ,[AssessmentHistoryId]
      ,[AssessmentHistoryHistoryAt])
SELECT        Id, 1 AS Expr1, '2021.11.24' AS Expr2, '2022.12.19' AS Expr3, Id AS Expr4, MIN(HistoryAt) AS Expr5
FROM            AssessmentHistories
WHERE        (HistoryAt > '2021.11.25') AND (Id IN (15960,12580,11926))
GROUP BY Id
```

**Comment by steinho** [comment]
Revisjoner ser ut til å være ok - den jeg sjekket: https://artsdatabanken.no/lister/rodlisteforarter/2021/12580

**Comment by steinho** [comment]
Lukker denne nå - Om det kommer behov for flere - lag ny issue som kan peke på denne for referanse: I beskrivelsen av den nye kan man peke via "hashtag" 492 - og vil få lenke ala denne: #492
