### ISSUE TITLE
Vurderinger mangler "siteres som"-boks

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#499]
En del vurderinger mangler helt siteres som - boks - deriblant øyenstikkere, døgnfluer, steinfluer, saksedyr, mudderfluer, nettvinger mfl. 

[Eksempel](https://artsdatabanken.no/lister/rodlisteforarter/2021/16496)

Edit: er et resultat av [https://github.com/Artsdatabanken/assessments-frontend/issues/188](https://github.com/Artsdatabanken/assessments-frontend/issues/188)

**Comment by helemork** [comment]
Heisann! Kan du komme med noen eksempler? Jeg har ikke klar å spore opp en eneste vurdering der dette er tilfelle.
Jeg gikk gjennom samtlige saksedyr uten å finne noen tilfeller, samt mange andre.
Uten eksempler kommer jeg ikke til bunns i saken.

**Comment by helemork** [comment]
Ok etter videre testing - alt finnes lokalt, men de finnes ikke i drift.
Så det må være en forskjell mellom drift og lokal kjøring. Skal se hva mer jeg kan finne ut.

**Comment by eirikn-artsdatabanken** [comment]
fungerte til meg også, men virker ikke når jeg oppdaterer datagrunnlaget (sletter de mellomlagrede filene, siden det har vært kjørt ny dump/transformering fra produksjonbasen siden sist)

sammenlignet filene og navn på "ExpertCommittee" (Ekspertgruppe) er ikke lengre synkronisert med navn i Excel-filen (ihvertfall i dette tilfellet, og antaglig flere)

altså, på vurderingen:
https://artsdatabanken.no/lister/rodlisteforarter/2021/16496
sier datamodellen/datagrunnlaget akkurat nå at ExpertCommittee = "**Øyenstikkere**", men i den litt eldre "dumpen" var satt til "**Døgnfluer, øyenstikkere, steinfluer, vårfluer**"

.. og i excel filen slår vi dette opp og finner ingen treff, siden det ikke er noen grupper som heter dette..

@KristineLund er det endret navn på Ekspertgruppe på vurderinger i produksjonsbasen på et tidspunkt for ikke så lenge siden?

Ulempen nå er at disse to datafilene ikke lengre er synkronisert (en generert fra produksjonsbasen koblet mot en laget manuelt) 

Vi må evt endre navn også i den manuelle filen med ekspertgruppemedlemmer

Dette var noe vi lagde i #72 første gang og er basert på en fil jeg fikk via teams, tror jeg

**Comment by KristineLund** [comment]
Tenkte meg det var noe sånt, ja. Vi hadde en runde* for ikke så lenge siden med å erstatte "," i "Døgnfluer, øyenstikkere, steinfluer, vårfluer" med "og" -> "Døgnfluer, øyenstikkere, steinfluer og vårfluer" men "Øyenstikkere" var jo ment som SpeciesGroup, ikke som ExpertCommittee...

*når vi uansett skulle endre på hydrozoer

Bare fortell meg hva jeg skal gjøre og hvor :)

**Comment by eirikn-artsdatabanken** [comment]
Filen som brukes for å koble ekspertgruppe og hente medlemmer må oppdateres, ganske sikker på at det er denne filen:

https://artsdatabankenno.sharepoint.com/:x:/s/Prosjekt-Visningavekspertvurderinger/EeyJSQmFhq9CtTgI33V7sI4B5u1NXPeuUWLbT5NhAjidEg?e=8Qr0R8

Vi bruker feltet "ExpertCommittee" for å koble riktig (fristende å koble med "SpeciesGroup", men da blander vi sammen feltene i de forskjellige systemene - siden vi har et felt i datamodellen som også heter "SpeciesGroup")

**Comment by eirikn-artsdatabanken** [comment]
.. hmm, det er også mulig at vi har kode som skal transformere ekspertnavn etc fra produksjonsbasen til vår modell - så det er kanskje heller det som har skjedd (er ganske sikker):

https://github.com/Artsdatabanken/assessments-frontend/blob/ec8ac2da5d2f55004c51ff83ee0710ca70cc1f4d/Assessments.Mapping/Helpers/SpeciesAssessment2021ProfileHelper.cs#L258-L258

**Comment by eirikn-artsdatabanken** [comment]
@KristineLund du må også i tillegg oppdatere filen med nytt navn, usikker på om det gjelder flere ekspertgrupper eller bare denne og kun for 2021?

**Comment by helemork** [comment]
Det stemmer at @steinho satte opp en del regler for ekspertgruppenavn. 
Har du kontroll på dette selv @eirikn-artsdatabanken og får fikset problemet denne gang, eller skal vi koble han inn? Hvis du finne ut en god måte å fikse det på er det veldig supert å legge inn en liten kommentar i koden på hva du gjorde om det oppstår igjen :)

**Comment by KristineLund** [comment]
> @KristineLund du må også i tillegg oppdatere filen med nytt navn, usikker på om det gjelder flere ekspertgrupper eller bare denne og kun for 2021?

jeg må innrømme at jeg har mista litt oversikten over hva vi har av options på ExpertCommittee i det som er nåværende versjon. Er det noe sted jeg kan hente ut alle unike ExpertCommittee i datamodellen så jeg kan oppdatere navnene i koblingsfila Eksperter alle år.xlsx i teamskanalen?

**Comment by eirikn-artsdatabanken** [comment]
du kan se disse som json her:
https://artsdatabanken.no/lister/api/Species2021?$count=true&$apply=groupby((ExpertCommittee))

her kan du også se datamodellen for vurderingen i lenken i beskrivelsen (den som mangler sitering):
https://artsdatabanken.no/lister/api/Species2021(16496)?$select=Id,ScientificNameId,ExpertCommittee

**Comment by eirikn-artsdatabanken** [comment]
litt status etter **mye** feilsøking:

har funnet endel issues og utfordringer knyttet til ekspertgrupper i transformeringen så dette problemet ligger nok bare i koden, sporet litt av når jeg trodde det var erstattet "komma" med "og"  (noe jeg ikke kan se er gjort hverken i koden eller produksjonbasen, ihvertrfall ikke på "Døgnfluer, øyenstikkere, steinfluer, vårfluer"..)

har laget en fiks, som gjør at vi må kjøre en ny "dump" og transformering av produksjonbasen

bør helst ta en gjennomgang med @steinho først og antagelig utsette publisering til mandag, har ikke helt god oversikt over bygging/ulike miljø og vil ikke potensielt ødelegge noe annet (vi bør teste løsningen litt først)

**Comment by eirikn-artsdatabanken** [comment]
har bygget til beta og det fungerer der nå: https://beta.artsdatabanken.no/lister/rodlisteforarter/2021/16496

**Comment by KristineLund** [comment]
Det ser veldig bra ut i betaversjonen! Har sjekket en del vurderinger og det ser riktig ut over hele fjøla :D
