### ISSUE TITLE
Kartvisning av Regioner og havområder 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#52]
- Trenger først en god visuell forklaring på havområdene
- Trenger videre å få laget dette som en bildemodell.
---
- [x] Lage kartvisning i svg for alle regioner
- [x] Legge til hovermarkering
- [x] Lage legende
- [x] Justere størrelsene på forskjellige skjermvisninger
- [x] Plassere på mobil
- [x] Hover-tekst <- region

**Comment by KristineLund** [comment]
For bakgrunn: gammel issue til innsynet på samme sak: https://github.com/Artsdatabanken/Risikovurderinger/issues/18

**Comment by KristineLund** [comment]
Det ville vært fint med en kartmodell som kan brukes til flere ting: 
- som forekomstkart på vurderingssiden (aller viktigst), f.eks.:
![fylkesforekomst assessmentview](https://user-images.githubusercontent.com/25904198/129007879-220c167a-2bca-4c8b-a664-303592b0e7e6.jpg)
- som illustrasjon på hvor i landet vi har flest trua og nær trua arter i [statistikkvisning](#42 )
![statistikkvisning fylker](https://user-images.githubusercontent.com/25904198/129008398-24fa4470-9950-49b8-afbd-19bcc7e08395.jpg)
- med mulighet til å gjøre små justeringer så vi kan bruke den som illustrasjon f.eks. på temasiden "Hvor finnes de truede artene?"

Ser ikke behov for fancy figurering. Burde være tilstrekkelig om vi har kontroll på fyllfarge og legend.

**Comment by helemork** [comment]
Splittet ut de elementene som ikke er prioritet 1 til egne issues, så kan denne lukkes.
