### ISSUE TITLE
Endre "Siteres som" for karplanter

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#521]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/61016662/145209479-38f3cea6-d25d-41f4-9a1f-1a9ba9cf6639.png">

Oppsettet for referanse for karplanter skal endres noe med tanke på rekkefølge på forfatterne. 
**NY**: Solstad H, Elven R, Arnesen G, Eidesen PB, Gaarder G, Hegre H, Høitomt T, Mjelde M og Pedersen O (2021, 24. november)

Hvem kan hjelpe til med det? @helemork @eirikn-artsdatabanken?

---
oppskrift: 
execelfilen endres ved at det legges til en ny rolle: "Nestleder"
vi sorterer med rekkefølge etter rolle (leder->nestleder->medlem), og så alfabetisk på etternavn

**Comment by eirikn-artsdatabanken** [comment]
ikke helt sikker på "oppskriften" her

om det skal være en (ny) egendefinert sortering, så kan man evt endre rekkefølgen i excelfilen (som er datakilden for dette, lagret i teams som "Eksperter alle år.xlsx") - og når det er gjort så må vi publisere denne filen på nytt og ta bort gjeldende sortering i kode (har vært endel justeringer på akkurat dette)

om vi skal skal gå for den løsningen bør man endre rekkefølgen på alle medlemmene i alle gruppene, slik at det kun er der sorteringen bestemmes (selv om vi sikkert kan lage kode som overstyrer for kun en gruppe(?), men synes ikke det er lurt med tanke på vedlikehold og at det blir ganske uoversiktlig)

**Comment by eirikn-artsdatabanken** [comment]
ps. jeg klarer ikke se om dette også gjelder en endring i forhold til rolle (leder/medlem) i tillegg til at man skal se bort fra alfabetisk rekkefølge?

**Comment by SiriKasperdatter** [comment]
Vi kan tenke på denne endringen som om vi har en nestleder, på en måte. Resten etter de to første skal fortsatt være alfabetisk. 

Er det sorteringen på PersonligKode i den fila du henviser til, du tenker på?

**Comment by eirikn-artsdatabanken** [comment]
nei, nå bruker vi følgende sortering (i kode): leder(er) først så medlemmer alfabetisk på etternavn

om vi skal endre på dette så kan vi evt bruke rekkefølgen i exceldokumentet (gjerne etter radnummer, dvs rekkefølgen det er lagt inn i radene), men vi kan også sortere på et annet felt om det er ønskelig
