### ISSUE TITLE
Ulike treff når man søker med og uten rangindikator

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#523]
Hvis jeg søker på noe under artsnivået med rangindikator får jeg ingen treff i det "globale" (?) søket,  altså søkeforslagene som kommer opp mens man skriver. 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/61016662/145424315-07e1d4d6-1657-4aae-bcfb-297a98fd741f.png">

Men trykker jeg enter får jeg treff **med** rangindikatoren. 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/61016662/145424415-7204d4ce-3571-4e62-b832-9938b0d63f34.png">

Er det vanskelig å få til at man får treff også i søkeforslaget med rangindikatorer? Fremstår litt merkelig at den ene ikke gir treff når rangindikatoren er inkludert i forslaget hvis jeg søker uten, og at den andre gir eksakt treff. 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/61016662/145424736-5a8c02d5-8a7d-46f8-b632-d40658504bc1.png">

**Comment by matssa** [comment]
Dette kan fikses. Grunnen er at søkeforslagene går mot artskart, for så å filtreres gjennom rødlistebasen. I artskart ligger ikke artene inne med rangindikator, så det vil ikke få noen treff. Hvis vi derimot gjør et søk mot både artskart og rødlista, og beholder alt i rødlista, pluss det som ligger i både artskart og rødlista burde vi få inkludert de med rangindikator.
