### ISSUE TITLE
Habitat

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#53]
Her er det en del ønsker for forbedring. Ref. samtale med @tovelitovela og kommentar fra @KristineLund som i stor grad samsvarer.

- [x] skjul hele greia for arter som ikke har utfylt noe habitat (det gjelder de aller fleste NA, NE og LC-arter, dvs. mange assessments) <-- Her kan vi faktisk sjekke om det er utfylt, og skjule den hvis det mangler. Det er allerede i eksisterende løsning.
- [x] Gå over og kontrollere NiN-mapping på alle elementene etter veilederen
- [ ] #69
- [ ] #70
- [x] Legg til midlertidig forklaring for hva habitat er som godt kan forbedres til senere
- [x] Vi ønsker også å skjule alle andre habitat for brukeren bak en se mer knapp.

**Comment by KristineLund** [comment]
Hiver inn tabell m. Rødliste-habitat til NiN koder m lenke [her ](https://artsdatabankenno-my.sharepoint.com/:x:/g/personal/kristine_bjornaas_artsdatabanken_no/EWTjd3eUMu5Eqc3Vs_zWnKQBqBBRsKVSmDqp5gmPtDKdnA?e=cxAk3t) i tilfelle noen behøver å slå opp kjapt. Fra NiN hovedtyper til Rødliste-habitat finnes i vedlegg på norsk veileder (men er ikke uttømmende for Rødliste-habitat)

**Comment by SiriKasperdatter** [comment]
Forslag til forklarende snutt om hva et hovedhabitat er. 
I 2010-lista står det: _Når det gjelder registrering av artenes leveområde (habitat), inkluderer dette bare de typer som er viktigst for arten (skal være relevant for mer enn 20 % av bestanden)._

Hva med noe sånt: "Arten lever i følgende hovedhabitat(er). Kun de viktigste habitatene er listet (relevant for mer enn 20 % av populasjonen)"?

**Comment by tovelitovela** [comment]
Ville det vært helt forbudt å bare skrive "De viktigste habitatene for arten."?

**Comment by SiriKasperdatter** [comment]
> Ville det vært helt forbudt å bare skrive "De viktigste habitatene for arten."?

Nei, vi kan godt gjøre det enkelt :) Men er det rart å ha "habitatene" hvis det bare er ett?

**Comment by helemork** [comment]
OK Jeg prøver meg basert på det dere skrev over og det vi hadde fra før (P.S: husk at ikke alle som forvirrer seg inn på rødlista vet hva habitat er, har vi en infoside om det vi kan linke til på ordet habitat?) Bold er der jeg mener det bør lenkes til infosider.

Artens **habitat** er dens viktigste leveområder. I vurderingene er det laget noen predefinerte habitat basert på inndeling etter **Natur i Norge (NiN)** systemet. 

Jeg synes kanskje at vi bør lage denne undersiden kalt habitat hvor vi skriver litt mer, blant annet det med 20% og full visning av alle. Kanskje lenke inn nin-kart eller no også.
