### ISSUE TITLE
Vurderinger som mangler sitering

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#539]
Sitering av ekspertkomitéen har falt ut for døgnfluer, kakerlakker, hydrozoer ++. Virker som om det gjelder de "fradelte" sammensatte artsgruppene.

**Comment by helemork** [comment]
Dette trodde jeg @eirikn-artsdatabanken hadde fiksa før ferien?

**Comment by eirikn-artsdatabanken** [comment]
vi henter medlemmer fra filen "Eksperter alle år.xlsx" i teamskanalen (generelt), kolonnene "ExpertCommittee" og "RodlisteAr" brukes for å kobler med en vurdering - virker som noen ekspertkomitéer har fått nytt navn uten at denne filen er oppdatert?

f.eks https://artsdatabanken.no/lister/rodlisteforarter/2021/33292 

"ExpertCommittee" er satt til "Hydrozoer", det er ikke et navn som finnes i excelfilen..

**Comment by SiriKasperdatter** [comment]
Hm, ok. Trodde det var på stell i den fila. Men ok, da blir det fort mitt oppdrag å fikse :)

**Comment by eirikn-artsdatabanken** [comment]
skal være fikset nå, lagt ut oppdatert versjon av filen
eks https://artsdatabanken.no/lister/rodlisteforarter/2021/33292
