### ISSUE TITLE
Endre innledende informasjon

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#54]
Ønsker å bytte ut de innledende setningene for samtlige kategorier, altså denne: 
![image](https://user-images.githubusercontent.com/61016662/124884087-3fb6c180-dfd2-11eb-9f84-d066430dd579.png)
 
Til: 
**NA**:	Arten er _ikke egnet_ NA for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**NE**:	Arten er _ikke vurdert_ NE for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**LC**:	Arten er vurdert til kategorien _livskraftig_ for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**DD**:	Arten er vurdert til kategorien _datamangel_ DD for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**NT**:	Arten er vurdert til kategorien _nær truet_ NT for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**VU**:	Arten er vurdert til kategorien _sårbar_ VU for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**EN**:	Arten er vurdert til kategorien _sterkt truet_ EN for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**CR**:	Arten er vurdert til kategorien _kritisk truet_ CR for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.
**RE**:	Arten er vurdert til å være _regionalt utdødd_ RE for Norsk rødliste for arter 2021. Rødlista for arter er en oversikt over arter som har risiko for å dø ut fra Norge.

**Comment by helemork** [comment]
Her har @KristineLund vært inne for å endre tekstene nylig, endring vises i fila https://github.com/Artsdatabanken/assessments-frontend/blob/master/Assessments.Frontend.Web/Views/Shared/glossary.json så jeg mistenker denne issuen nå har blitt redundant. 

Jeg tenker små tekstendringer må dere gledelig gjøre selv ved å :
1. lage en ny grein
2. redigere json-filene og skrive en liten commit beskjed om hva som er endret
3. enten sette opp en pull request fra greina eller si fra så fikser jeg det.
Hvis dere trenger hjelp med noen av stegene er det bare å si fra.

**Comment by helemork** [comment]
Antar denne ble fullført i endringene i går, så setter den som lukket. Bare å åpne igjen om det er feil. :)
