### ISSUE TITLE
Endre fremmedartsavsnitt

### ISSUE THREAD

**Issue by SiriKasperdatter** [Artsdatabanken/assessments-frontend#559]
Teksten i avsnittet: 
Hvorfor er arten ikke egnet NA?
**Arten er fremmed, og ble enten etablert innenfor vurderingsområdet etter år 1800 eller antas å kunne etablere seg innen 50 år (dørstokkart).**

Byttes ut med 

**Arten er fremmed og vurdert som selvstendig reproduserende etter år 1800, eller arten er fremmed og antas å kunne reprodusere selvstendig innen 50  (dørstokkart).**
- med hyperlenken https://www.artsdatabanken.no/Pages/241513/Fleire_artar_bankar_paa lagt til på ordet (dørstokkart).

**Comment by helemork** [comment]
antar det skal stå 50 år på den siste også. 
fikses i ny grein.

**Comment by SiriKasperdatter** [comment]
Ja, uups. Bra iallfall noen har øynene med seg :)
