### ISSUE TITLE
Søkeforslag feiler

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#564]
Søket på 'gaupe' sender denne requesten hos meg (Google Chrome):
"https://artsdatabanken.no/lister/rodlisteforarter/2021//suggestions?search=gaupe"
Det er altså to '/' før "suggestions" i url-en. 

Når jeg kjører lokalt har jeg ikke dette problemet. En replace("//suggestions", "/suggestions") bør fikse dette problemet. 
Ved testing i Microsoft Edge er dette ikke et problem.

**Comment by helemork** [comment]
Denne er ikke helt i mål ennå. 
Fix ligger på beta nå,
men selv om å søke ikke lenger kræsjer, gir treffet i droppnedlista det. Den tar brukeren til /lister/rodlisteforarter/2021//26449 som er en slash for mye. er nok relatert.
