### ISSUE TITLE
Feil i eksporten

### ISSUE THREAD

**Issue by SnorresKongesaga** [Artsdatabanken/assessments-frontend#572]
Se f.eks. snøugle: 

Det mangler tekst i eksporten både midt i og på slutten sammenlignet med nettversjonen https://artsdatabanken.no/lister/rodlisteforarter/2021/28799

Gjelder flere arter. Ser ut som eksporten kutter etter tegnene "(<" 
 
"arten kvalifiserer dermed til rødlistekategori kritisk truet CR etter kriteriet D1 **(<** 50 reproduserende individer)"

--

- [x] ta også bort html fra "Begrunnelse nedgradering av kategori" (RationaleCategoryAdjustment)

**Comment by eirikn-artsdatabanken** [comment]
virker som det først og fremst gjelder feltet "Kriteriedokumentasjon" ("ExpertStatement" i datamodellen)

koden vår renser feltet for html, den tar da også bort tekst som kommer mellom tegn med "<" og ">"..
https://github.com/Artsdatabanken/assessments-frontend/blob/0b7b1fe3886d0bb014a1fd9d99735209af53b0a5/Assessments.Mapping/SpeciesAssessment2021ExportProfile.cs#L99-L99

bør bytte til en metode som beholder tekst med klammer

**Comment by steinho** [comment]
Er denne nødvendig?
Brukes kun i mapping til excel på ett felt - ExpertStatement -- og dette blir allerede rensket for unødvendig html på forhånd:
                .ForMember(dest => dest.ExpertStatement, opt => opt.MapFrom(src =>HtmlCleaner.MakeHtmlSafe(src.Kriteriedokumentasjon, true)))

**Comment by eirikn-artsdatabanken** [comment]
eksporten skal ikke inkludere html

transformeringen (HtmlCleaner.MakeHtmlSafe) tar ikke bort html tagger, innholdet i feltet kriteriedokumentsasjon blir f.eks slik (utdrag): 

`<p><b>Utbredelse og økologi: </b>Snøugle (<i>Bubo scandiacus</i>) ..`

Jeg gjør et forsøk på å endre metoden til å fjerne html, men beholde tekst

**Comment by steinho** [comment]
> eksporten skal ikke inkludere html
> 
> transformeringen (HtmlCleaner.MakeHtmlSafe) tar ikke bort html tagger, innholdet i feltet kriteriedokumentsasjon blir f.eks slik (utdrag):
> 
> `<p><b>Utbredelse og økologi: </b>Snøugle (<i>Bubo scandiacus</i>) ..`
> 
> Jeg gjør et forsøk på å endre metoden til å fjerne html, men beholde tekst

Ah - forstår... Kanskje best med helt ren tekst der ja
