### ISSUE TITLE
Forbedre transformasjon av "previous assessments" for 2018

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#658]
- [x]  implementer category som enum (implementert i #657
- [x] beregn riktig kategori basert på RiskLevel, MainCategory og MainSubCategory
- [x] legg til lenker til vurderingene
- [x] ta hensyn til at  kategori kan mangle på tidligere vurderinger (være blank) 

Formler for beregning av kategori: 
- [2018 ](https://github.com/Artsdatabanken/Fremmedartsbase2023/blob/65212142a2dbb29317a0cc94bfde26688ab1bc67/Prod.Api/Helpers/ExportMapper.cs#L31-L72)

Enkelte verdier trenger vi kun for beregning av kategori for 2018 (ikke 2012!)- Dette gjelder SpreadRiskLevel, EcologicalRiskLevel, MainCategory, MainSubCategory og DecisiveCriteria. Disse behøves i hovedsak for statistikkformål.

---

2012 bruker taksonid som id
2018 bruker "FA3/N/105" som id

eksempel for lenker "Chenopodium borbasioides":
- https://artsdatabanken.no/fremmedarter/2018/N/105
- http://databank.artsdatabanken.no/FremmedArt2012/N61354

**Comment by AneMarlene** [comment]
Kode for Category i 2018 finnes på l. 31 - 72 her: [Fremmedartsbase2023\Prod.Api\Helpers\ExportMapper.cs ](https://github.com/Artsdatabanken/Fremmedartsbase2023/blob/main/Prod.Api/Helpers/ExportMapper.cs)

**Comment by eirikn-artsdatabanken** [comment]
må legges til for 2012 når formel er tilgjengelig
