### ISSUE TITLE
byggge develop - kunne se fremmedartslista 2023 (både visning og api)

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#679]
- [x] få kontroll på miljøvariabler slik at vi kan bygge til alle miljø, og bruke det til å bestemme hva som skal vises
- [x] gjøre om "NotReadyForProduction" funksjonen for sjekk mot miljø
- [x] oppdatere readme for bygging (manuelt i slack) - og hvilke miljø som brukes til hva (develop branch default)

tilgjengelig utenfor kontor/vpn:
- https://artsdatabanken.no/lister/ (production)
- https://beta.artsdatabanken.no/lister/  (staging) -> **bør settes til production**

ikke tilgjengelig utenfor kontor/vpn:
- https://assessments-fe-dev.test.artsdatabanken.no (staging)
- https://assessments-fe.test.artsdatabanken.no (staging)
- https://assessments-fe.artsdatabanken.no (production) -> kan brukes til å teste kode for "production"?

**Comment by steinho** [comment]
Anng Environment variabler:
beta.artsdatabanken.no - står til Staging

På prod - www.artsdatabanken.no - står det til Production:
![image](https://user-images.githubusercontent.com/3253353/201534230-cc77c6ce-9c6f-449b-a971-e34c4b6b7db3.png)

**Comment by eirikn-artsdatabanken** [comment]
kan ha "Production" på beta også, og skulle hatt "Staging" på https://assessments-fe-dev.test.artsdatabanken.no
er sikkert en variabel for docker

**Comment by eirikn-artsdatabanken** [comment]
beta.artsdatabanken.no bør også ha "Production"

**Comment by steinho** [comment]
> beta.artsdatabanken.no bør også ha "Production"

Skal være endret nå: https://beta.artsdatabanken.no/lister/
