### ISSUE TITLE
Eksporten - Bruke displaynavn på AlienSpeciesCategory

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#685]
I eksporten ønsker vi å bruke etablerte norske navn på verdiene et objekt kan ta, og ikke de engelske kodenavnene. Dette fordi det er de norske navnene som kommuniseres og brukes utad. 

For enumen AlienSpeciesCategory vil dette si at vi ønsker å vise fram displayname for hver verdi, og ikke selve verdien.

**Comment by eirikn-artsdatabanken** [comment]
kan gjøre denne når "AlienSpeciesCategory" er gjort om til enum i #684 

 https://github.com/Artsdatabanken/assessments-frontend/blob/f676e8fa3040998da0fce891c7d6c40f5692a350/Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs#L11
