### ISSUE TITLE
Habitatbeskrivelser

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#69]
Få inn en beskrivelse av habitatene, da de tross alt skiller seg fra NiN. @SnorresKongesaga
Har midlertidig gjenbrukt beskrivelsene fra 2015, men det kan jo være endringer på innholdet siden da.

Juster gjerne rett i json-fila som per nå ligger her:
https://github.com/Artsdatabanken/assessments-frontend/blob/master/Assessments.Frontend.Web/Views/Test/partials_2021/habitat.json

Trykk på rediger, gjør endringer, og fyll ut commit-skjemaet nederst. Velg å opprette ny branch.

**Comment by KristineLund** [comment]
gjorde noen småendringer på habitat.json i begynnelsen av uke 32 som er rullet ut nå. Gjør gjerne kvalitetssjekk @SnorresKongesaga

**Comment by SnorresKongesaga** [comment]
Sjekket og funnet i orden. Mulig man skulle lagt inn alle hovedtyper under marint, ferskvann og våtmark også under de representative hovedhabitatene
