### ISSUE TITLE
URL-oppsett

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#7]
## ENDELIG KONKLUSJON:

Årets liste:
- [ ] artsdatabanken.no/rodlisteforarter/2021 (blank liste for både Norge og Svalbard)
- [ ] artsdatabanken.no/rodlisteforarter/2021/ID (blank liste for både Norge og Svalbard)
- [ ] artsdatabanken.no/rodlisteforarter/2021/Norge (blank liste for Norge)
- [ ] artsdatabanken.no/rodlisteforarter/2021/Svalbard (blank liste for Svalbard)

Andre relevante url'er:
- [ ] artsdatabanken.no/rodlisteforarter/ (samleside med årstall, som sender bruker til riktig år etter ønske)

REDIRECTS:
- [ ] artsdatabanken.no/rodliste -> artsdatabanken.no/rodlisteforarter/
- [ ] artsdatabanken.no/rodlista -> artsdatabanken.no/rodlisteforarter/

Prioritering 5:
- [ ] artsdatabanken.no/rodliste/blablabla (ikke eksisterende)  -> artsdatabanken.no/rodlisteforarter
- [ ] artsdatabanken.no/rodliste/2021/blablabla  -> artsdatabanken.no/rodlisteforarter/2021 med søk etter "blablabla"

Fremtidige lister:
P.S. En ID for 2021 er ikke nødvendigvis samme art i 2015, 10 eller 6.
- [ ] artsdatabanken.no/rodlisteforarter/2015 (kommer etter hvert)
- [ ] artsdatabanken.no/rodlisteforarter/2010
- [ ] artsdatabanken.no/rodlisteforarter/2006  

-------
## ORGINAL TEKST FØR EDIT

Det er flere ting å ta hensyn til mtp. url-struktur. 

## HOVEDANKER
Det første er hovedankeret. I diskusjoner har vi foreslått å benytte artsdatabanken.no/rodlista. Men vi har jo både rødliste for arter og natur, så denne er ikke entydig. Vi bør derfor ha en grunn-url i bunn som er entydig. Såfremst vi ikke skal ha en felles samlingsside for rødliste på toppen, bør vi holde oss til et

forslag 1: Kun et ord som fult reflekterer hvilken liste vi er på

A) rodlisteforarter/
B) rodlistearter/
C) artsrodliste/

forslag 2: Et øvre ledd som sender brukeren til riktig liste, da vil vi også ha et øvre ledd. Det kan jo være utelukkende en lenke til de to undertypene av rødliste og er sånn sett ikke et problem. Kanskje greit egentlig. 

D1) rodlista (lenker til de to undersidene, hvorav naturtyper lenker tilbake til den gamle løsningen)
D2) rodlista/arter 
D3) rodlista/naturtyper 

## Artsid?
Hvordan skal vi referere til og lenke mellom artene?
Inntil videre refererer jeg til alt av arts-relatert id/navn som art.

- Jeg vil anta latinsknavnid/vitenskapelignavn-id er ønskelig å benytte for stabilitetens skyld.
- Hvordan håndtere navneendring mtp. url?
- Hva får vi om vi søker på vitenskapelig  navn? Jeg mener vitenskapelig navn bør returnere det samme som å søke i listen på dette latinske navnet ville ha gjort, altså behandles som et filter. Da vil arter med duplikate navn og flere vurderinger listes opp så brukeren selv kan gå til ønsket vurdering.

## Videre struktur
- hovedanker bør ta oss til listevisning for gjeldende vurderinger, og med store fine lenker til de tidligere listene
- hovedanker/år bør ta oss til rødlista for dette året. - som et filter i listevisningen
- hovedanker/år/svalbard bør returnere alle treff for svalbard i gitt år - som et filter i listevisningen
- hovedanker/år/norge bør returnere alle treff for norge i gitt år - som et filter i listevisningen
**- hovedanker/år/art/norge bør returnere artens vurdering i norge i gitt år - Dette er en entydig vurdering.**
- hovedanker/art er foreslått å returnere en av gjeldende vurderingene for arten (jeg antar norge), men burde returnere begge de gjeldende vurderingene av arten. Enten i form av lenker videre til de to vurderingene, eller presentasjon av begge under hverandre med Norge på topp. Alternativt kunne den ledet til filter for søk.
- hovedanker/år/art Se over, men for gitt år.
- Alle vurderingssidene må inneholde tydelige lenker for å bla mellom år og lokasjon

**Comment by SnorresKongesaga** [comment]
Mange gode forslag Helen. Kun noen kommentarer fra meg:

### HOVEDANKER: 
Vi har (per i dag) ingen felles side/plattform for arter og naturtyper. Med andre ord, www.artsdatabanken.no/arter og www.artsdatabanken.no/naturtyper hadde vært er en mer logisk faglig inndeling. Støtter derfor forslag 1

### Artsid?
Punkt 3: Det er  enklere å tenke på at en art kan ha flere vurderinger i stedet for duplikate navn. En art kan i teorien ha opptil 11 vurderinger vurderinger knyttet til seg: rødlista Norge/Svalbard 2015, 2021, Fremmedartslista 2018 etc.

### Videre struktur
Jeg heller nok mot at hovedanker bør entydig gi gjeldende vurdering jfr. punktet over om at en art kan ha 11 vurderinger (et tall som bare kommer til å øke med årene). Kom gjerne med forslag til hvordan de skal se ut og fungere
hovedanker/art bør gi vurdering for både N og S (tenkt isbjørn; hovedanker/isbjørn må gi et treff uten at man trenger vite at arten er vurdert for Norge eller Svalbard.

**Comment by helemork** [comment]
Da har vi kommet litt videre, @SnorresKongesaga så takk for inputs. 

## HOVEDANKER: 
Jeg velger isåfall å gå for "rodlistaforarter", alternativ 1A om det ikke kommer andre/bedre forslag.


## Artsid
Enig med det, men uavhengig av hvordan man tenker på det må et søk på artsnavn returnere noe. I filteret kan man ikke vite hva brukeren er på jakt etter og derav er det naturlig å returnere alle mulige vurderinger. :) 

## Videre struktur. 
Her forstår jeg ikke helt hva du mener? Utav det jeg skrev over bør disse url'ene alltid være entydige til én vurdering:

- rodlisteforarter/år/norge/vitenskapelignavnid
- rodlisteforarter/år/svalbard/vitenskapelignavnid

Spørsmålet er mer hvordan vi skal returnere data for 
- rodlisteforarter/år/vitenskapelignavnid 
For som du sier bør vi jo returnere begge vurderignene her, men det er flere forhold å tenke på. 
En ting er hvordan vi viser det frem, der kan vi gjøre akkurat det som passer oss, men om noen benytter api for å bare hente ut vurdering er det litt viktig å ha en så tydelig struktur som mulig, så andre som henter ut vet om det finnes en eller to vurderinger for en art. Folk flest tenker kanskje ikke på at svalbard vurderes separat.

For ganske mange arter vil det da finnes to vurderinger. Jeg ser for meg de burde fått tilbake et resultat som ser omtrent sånn ut: artsid{[..],kategori:{ svalbard: LC, Norge: CR}[..]}. Og at denne strukturen er fast for alle arter, slik at enhver som henter ut data er tvunget til å enten ta ut begge eller presisere hvilken de vil ha. Om jeg ikke ar misforstått helt (mulig jeg har det og det er visningen som gjør det slik), levertes data i 2015 på formen vurderingsid{[navneinfo...],kategori[...],[artsgruppe:pattedyr(svalbard)]...} så joda, én id var da entydig med et resultat, men det var i 2015 umulig å få opp begge vurderingene på en art på en url. Som vil si at man på forhånd måtte vite om man var på fastlandet eller ikke.

Så for din problemstilling
- Når jeg søker på "isbjørn" i rødlista 2015, får jeg utelukkende opp en vurdering, som jeg antar er for svalbard. Det gjør jo saken ganske grei, for da er det bare ett resultat. Men betyr det at isbjørn da ikke ble vurdert i norge? Kun svalbard? I mitt hode burde da isbjørn/norge returnert NA/null eller ikke vurdert. Det dere mener er riktig. Det samme som å søke på dompap/svalbard bør gi som resultat. Fravær av vurdering er jo tross alt også en vurdering :) (Skriver false i eksempelet nedenfor bare for å holde det enkelt, men samma for meg hva den faktisk gir som svar så lenge det er noe)

1. rodlista/2021/isbjørnnavnid bør returnere {Kategori:{Svalbard:VU, Norge:false}}
2. rodlista/2021/isbjørnnavnid/Svalbard bør returnere {Kategori:VU}
3. rodlista/2021/isbjørnnavnid/Norge bør returnere {Kategori:false}

- For fjellrev derimot, er det to svar i lista med to kategorier, og forrige gang var det løst med /norge/artsid. Det er i og for seg greit, men det er ingen måte å bare skrive fjellrevid og få begge på en gang, da må man gå til begge hver for seg. Og da må man som bruker vite det finnes to vurderinger. 
1. rodlista/2021/fjellrevnavnid bør returnere {Kategori:{Svalbard:LC, Norge:CR}}
2. rodlista/2021/fjellrevnavnid /Svalbard bør returnere {Kategori:LC}
3. rodlista/2021/fjellrevnavnid /Norge bør returnere {Kategori:CR}

I tabellvisningen mener jeg det ikke bør vises som to linjer med samme navn, da det kan implisere to arter, men med en linje med to underlinjer. Se eksempel. Sier ikke det skal lages i paint og se akkurat slik ut, men mer som prof of concept. Dette for å tydeliggjøre at det er samme art. For som nevnt tidligere kan jo ting hete det samme men ikke være det, og da ville de jo ikke bodd på samme linje.  

![bilde](https://user-images.githubusercontent.com/17450081/120979744-3093e800-c776-11eb-837e-50a8bc5af7c1.png)

**Comment by helemork** [comment]
NE og NA
ikke vurdert og ikke egnet

**Comment by bugdriven** [comment]
Vil legge til at arter kan ha flere vurderinger enn det som er nevnt her. Hvis arter blir slått sammen kan, og vil, vi ha flere vurderinger på samme art i samme liste. Det gir en viss utfordring i forhold til formidling vil jeg tro.

**Comment by bugdriven** [comment]
En (sterk) kommetar til id på vurdering. Vurderinger bør ha en vurderings-id og ikke være knyttet til artsnavn, takson e.l. Jeg gjorde den tabben i rødlista 2015 å knytte vurderingen til taxonId. Det var et feilgrep. Å knytte vurdering til artsnavne eller navne-id ville vært litt bedre, men ville fortsatt vært feil. Det er viktig å  se på en vurdering som en egen entitet, et dokument. Ideelt sett et uforanderlig dokument som er publisert med forfatter og dato. Denne vurderingen er knyttet til en art, men egentlige er denne knytningen ikke fast. I senere lister har vi brukt konseptet "vurdert latinsknavn id" "vurdert latinsknavn" mm. i tilegg til latinsknavn og latinsknavn id. "Vurdert" vil bety hva navnet var når eksperten gjorde vurderingen. 
I dag ingekserer vi på feltet for latinsknavn (ikke "vurdert") og oppdaterer dette feltet til gjeldende taksonomi.
En tanke er å opprette en resolvertjeneste som finner vurderingsId for vurderinger fra alle lister.
