### ISSUE TITLE
Fremmedartene trenger ekspertgrupper med navn på medlemmer

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#709]
I Rødlista er det gjort noe greier for å få frem ekspertgruppene. Vi må kanskje gjøre det samme for fremmedartene?
Ekspertgruppemedlemmene trengs for å sitere vurderingene.

Hentes fra databasen (UserRoleInExpertGroups -> WriteAccess = True)
Leder = User -> IsAdmin = True

**Comment by eirikn-artsdatabanken** [comment]
høres ut som en god ide, det er allerede gjort litt kode i #707 for dette
bør diskutere litt løsning, om vi skal hente dette fra databasen og ikke basere det på excel (som i rødlista)

**Comment by eirikn-artsdatabanken** [comment]
usikker på om vi skal bruke initialer, og hvordan
@AneMarlene  bør gå gjennom denne og sjekke at data/filter ble riktig
