### ISSUE TITLE
Legge til kategori og lenke for tidligere vurderinger i 2012

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#711]
trenger formel for beregning av kategori, og logikk for å vite om det er svalbard eller norge til lenken

#658

**Comment by steinho** [comment]
Jeg ser det er dårlig tilgjengelig - må tilbake til en sql database fra2012 - der id - f.eks. 152 for abies alba - som er referert i historikken på vurderingen nå -  er koblett til region og noe som er kalt taxonomicid (taxonid) 63753. Dette gir url /N63753.

Prøve å populere inn dette i prod-databasen slik at det kan taes med i transformasjonen...
