### ISSUE TITLE
"Siteres som"- boks

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#72]
_Oppdatert etter diskusjoner med Fremmedartsgjengen og kommunikasjon:_
Vi bør ha med en "Siteres som"-boks helt nederst på visningen av hver enkelt vurdering (assesmentview)

Siden siteres som:
"Ekspertkomiteleder", "Ekspertkomitemedlem_1" ... og "Ekspertkomitemedlem_n" (2021, 24. november). "Artsgruppe" ("ArtsgruppeVitenskapeligNavn"): Vurdering av "NorskNavn" "VurdertVitenskapeligNavn" for "AssessmentAreaLong". Norsk rødliste for arter 2021. Artsdatabanken. "permanent lenke til vurderingssiden"

--der AssessmentAreaLong er "Norge med havområder" hvis VurderingsContext =N og "Svalbard" hvis VurderingsContext=S

Eks. for gulspurv:
Siden siteres som:
Stokke BG, Jacobsen KO, Solvang R, Dale S, Lislevand T og Strøm H (2021, 24. november). Fugler (Aves): Vurdering av gulspurv _Emberiza citrinella_ for Norge med havområder. Norsk rødliste for arter 2021. Artsdatabanken. [https://assessments-fe.test.artsdatabanken.no/test/30020?year=2021](url)

_EDIT:  ja takk til DOI - hvis det lar seg gjøre, men DOI kan ha lav prioritet når vi har permanent lenke.

@eirikn-artsdatabanken lager navne-strengen (altså det før årstall) basert på koblinga i #119

**Comment by helemork** [comment]
Jeg trodde vi kanskje skulle ha doi på disse? @olsoybakk @steinho ?

**Comment by KristineLund** [comment]
Se excel-fil på teams-området, t.o.m. rad 140 for gjeldende vurderinger i 2021. Bruk kolonne ExpertCommittee for match. Se siteringseksempel over for format

Hvis mulig, spesialregler: 
- Hvis ExpertGroup= Fugler og AssessmentArea= S -> Strøm H som førsteforfatter (pri3)
- Splitt fisker inn i ferskvannsfisker og marine fisker med ulike forfattere (pri3)

**Comment by eirikn-artsdatabanken** [comment]
"ArtsgruppeVitenskapeligNavn" må legges til når det er på plass i datamodellen

**Comment by helemork** [comment]
Spørsmål om formattering: nå ser det ut som det ikke er noe italics i eksempelet (utover artsgruppe). Jeg merger den derfor inn as is, men jeg antar vi følger et oppsett som skal putte deler av teksten i kursiv? Isåfall, bare si i fra så fikser jeg det ganske fort.

**Comment by KristineLund** [comment]
Ser ut som rekkefølgen på ekspertkomitémedlemmene i "sitering"-boksen ble alfabetisk i versjonen som ble rullet ut (øverste skjermdump). I assessment.fe.test (under) var det riktig rekkefølge - med ekspertkomitéleder først. 
![image](https://user-images.githubusercontent.com/25904198/143827496-f3951754-2f0a-4659-993d-11a6805002ab.png)
![image](https://user-images.githubusercontent.com/25904198/143827686-edbaf511-2ebb-4e38-9a64-7bb909f1ab9f.png)

**Comment by helemork** [comment]
@KristineLund  kopi av #484
Mener du det var riktig på alle før, eller bare denne? Om komiteleder alltid var riktig kan jeg jo sortere fra andre element fremfor første f.eks :)

**Comment by KristineLund** [comment]
Ser ut som det var riktig rekkefølge på stort sett alle før. Men oppdager først nå at det er en del vurderinger som helt mangler siteres som -boks :o - deriblant øyenstikkere, døgnfluer, steinfluer, saksedyr,
