### ISSUE TITLE
Artsside - Utbredelse i Norge

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#736]
For alle risikovurderte arter (dvs. alle utenom de med Category == "NR"), så skal informasjon om forekomstareal i Norge samt kart over regionvis utbredelse vises fram. Dette er viktig bakgrunnsinformasjon som for enkelte metoder også inngår direkte i risikovurderingen. 

Kartene kommer det egne issues på, men plasseringen av de er vist i dokumentet. Alle fritekstfelt og felt som vises i tabeller ligger klar på modellen. 

[Artsside_Utbredelse_Norge.docx](https://github.com/Artsdatabanken/assessments-frontend/files/10351989/Artsside_Utbredelse_Norge.docx)

**Comment by helemork** [comment]
![bilde](https://user-images.githubusercontent.com/17450081/210769910-432a7849-79a3-467e-991f-73f0cf0328d2.png)
Her er det noe feil i tabellene.

**Comment by AneMarlene** [comment]
@helemork . Bra du stiller spørsmål. Dokumentet (øverst i issuet) er oppdatert med rett tabell for dørstokkarter (den øverste raden var feil, men resten var rett).
