### ISSUE TITLE
Oppdatere kart til fremmedartslista 2023

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#738]
Relatert til #736 
Vi trenger å splitte nord- og sør-trøndelag i kartet. 
Bruk det samme kartet som rødlista.
Gi et pip dersom du ser at det ikke blir noe problem å lage mer enn en strek, så kan jeg lage grensa med litt større oppløsning.
Her er et utsnitt som illustrerer hvor grensa skal gå. Grensa er tegna i gult:
![image](https://user-images.githubusercontent.com/15391193/203810863-cc579e94-084f-470c-80c6-5cc0ccfb2308.png)

**Comment by helemork** [comment]
Har nå splitta Trøndelag i nord og sør per grensene fra 2018.
Men, usikker på hvordan vi gjør det med havområde for nord og sør-trøndelag, da jeg trenger er kildekart for dette for å kunne tegne det inn. Norgeskart kommer med disse grensene, men ikke for 2018, bare nåværende.

**Comment by matssa** [comment]
Slik jeg har forstått det så er det kun landområdet som skal deles opp. Du kan høre med @AneMarlene om dette.

**Comment by helemork** [comment]
kystlinja tilhører landområdet, så den må splittes om den skal med. men klarte å google meg frem et screenshot fra kartverket [(her)](https://beta.sildelaget.no/media/25279152/Skjermbilde%202013-04-22%20kl.%2011.28.53.png) så da er det i boks. Testa opp mot rødlistevurderingene siden FA-kartet ikke er i bruk ennå, og det ser bra ut. 

Avventer videre tweaks til jeg har hørt mer om hva annet som skal justeres. :)
