### ISSUE TITLE
bug(?) i filtreringen når man aktiverer > 1 filter fra ett tema

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#739]
Det går fint å aktivere flere filtre så lenge de er plassert under ulike "filtertema" (eks. aktivere risikokategori "LO" sammen med taksonomisk nivå "Art"). 
MEN hvis jeg aktiverer flere filtre under ett tema som gir flere treff enn det som vises på én side, så kan jeg ikke velge en annen side/bla meg bortover sidene uten at siden glemmer filtreringen og gir meg uventet resultat. 

Eksempel: 
1. Ane ønsker å se arter i risikokategoriene NK og LO (so far, so good): 
![image](https://user-images.githubusercontent.com/58254444/204050327-cb84938b-183f-4c77-85bc-b3aa0ce05ba0.png)

2. Ane ønsker så å se hvilke arter som ligger på side 2 (eller en vilkårlig annen side):
<img width="391" alt="image" src="https://user-images.githubusercontent.com/58254444/204050415-1605bcaf-f7f6-4b81-8933-4cc825b08543.png">

3. Ane forventer ikke dette på side 2 (eller en vilkårlig annen side): 
![image](https://user-images.githubusercontent.com/58254444/204050472-06c03603-a77b-45c8-943b-74d3714b2692.png)

**Comment by eirikn-artsdatabanken** [comment]
?Name=&SortBy=ScientificName&Meta=Visited&Meta=scroll_119&IsCheck=Area&IsCheck=Category&Category=HI&Category=PH&IsCheck=ttn&IsCheck=DecisiveCriterias&IsCheck=dcin&IsCheck=dcipah&IsCheck=dcok&IsCheck=eds&IsCheck=ccke&IsCheck=sal&IsCheck=sin&IsCheck=skr

?Page=2&SortBy=ScientificName&Meta=Visited,scroll_119&IsCheck=Area,Category,ttn,DecisiveCriterias,dcin,dcipah,dcok,eds,ccke,sal,sin,skr&Category=HI,PH
