### ISSUE TITLE
Artsside - klimaeffekter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#755]
For risikovurderte arter (= ikke NR), skal vi formidle informasjon om delkategorien på de to aksene (invasjonsaksen og økologisk effektaksen) er påvirket av klimaendringer eller ei. 

Gjerne fjern "RiskAssessment" fra de tre feltene når du først er i gang (iht #749) om du gidder :D

Oppskriften finner du (kanskje til og med nesten feilfri) her:

[Artsside_Klimaeffekter.docx](https://github.com/Artsdatabanken/assessments-frontend/files/10169759/Artsside_Klimaeffekter.docx)

**Comment by matssa** [comment]
Denne ble gjort i #804. Lukker den nå.
