### ISSUE TITLE
Artsside - geografisk variasjon i risiko

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#756]
For risikovurderte arter (= ikke NR), skal vi formidle informasjon om risikokategorien kunne vært lavere i deler av artens forekomstareal. Denne informasjonen er viktig og skal også angis i kortfattet versjon oppe i "cardet"/toppen av vurderingen (annet issue).

Gjerne fjern "RiskAssessment" fra feltene når du først er i gang (iht #749) om du gidder :D

Oppskriften kan ikke vente på å bli brukt og ligger her:

[Artsside_Geografisk variasjon.docx](https://github.com/Artsdatabanken/assessments-frontend/files/10170027/Artsside_Geografisk.variasjon.docx)

**Comment by helemork** [comment]
Mellom klimaeffekt og utberedelse
