### ISSUE TITLE
Risikomatrisen

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#758]
Lag fremvisning av risikomatrisen på vurderingssiden

**Comment by helemork** [comment]
Har nå kopiert inn matrisa fra 2018.
Hvilke felter er det som skal matches opp mot risikofelt i tabellen, og har vi en rask forklaring på hva som må til for å sette de riktige feltene?

Jeg ser det i den andre er både hel- og stiplet linje som jeg antar har en forklaring. Denne trenger jeg for å lage det riktig, men den burde også følge figuren slik at å lese tabellen ikke er forebeholdt eksperter som vet hva det betyr :)

**Comment by AneMarlene** [comment]
@helemork Jeg kan forklare det med hel og striplet linje, og delvis hvor du finner data på strak arm her: 

1. Hel linje - det angir det beste anslaget på plassering i matrisa og er det som bestemmer kategorien. Du finner denne ruta ved hjelp av feltene ScoreInvasionPotential (x-aksen) og ScoreEcologicalEffect (y-aksen).
2. Striplede linjer - dette angir usikkerheten. Den kan gå to (fire) veier fra ruta med det beste anslaget: horisontalt (x-aksen) eller/og vertikalt (y-aksen). Den kan ikke gå på skrå fra det beste anslaget. Her er det litt mer arbeid og logikk for å finne fram til tallene (spesielt på x-aksen - A-C-kriteriene), men selve dataen finnes i lista AlienSpeciesAssessment2023Criterion Criteria. For y-aksen er det likevel relativt enkelt å finne usikkerhet til matrisa: Finn fram til den/de av kriteriene **D-I** som har høyest Value. Hvis UncertaintyValues.Length > 1 for denne / en av disse, skal UncertaintyValues for den/de relevante kriteriene vises som usikkerhet i matrisa på y-aksen (vertikalt i matrisa). Hvis  UncertaintyValues.Length == 1, så skal det ikke vises fram noe usikkerhet på y-aksen.

**Comment by AneMarlene** [comment]
@helemork en kommentar til når det gjelder hel vs. striplet linje: Akkurat layouten kan det hende at headspin snur på hodet...men mot innsynet forholder vi oss til det som blir enklest. Personlig synes jeg den "hele" stripen er alt for anonym/lite fremtredende, men jeg har ikke noe godt alternativ i farta :)

**Comment by AneMarlene** [comment]
VI ønsker litt forklaring på aksene til matrisa, ala slik det er i FAB: 

![image](https://user-images.githubusercontent.com/58254444/211529231-313f2dc9-6bc8-4431-b5b5-ff5fd83ae1fe.png)
