### ISSUE TITLE
Artsside - Hva forklarer artens risikokategori - avgjørende kriterier - invasjonspotensialet - A-kriteriet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#759]
Kun for risikovurderte arter (ikke NR)!

Artens avgjørende kriterier for invasjonspotensial (A, B og C-kriteriet) må formidles. På A-kriteriet kan eksperten velge mellom 3 ulike estimeringsmetoder, og innholdet som vises fram avhenger både av metode valgt og av type fremmedart. 

...to be continued...

**Comment by matssa** [comment]
Er ikke denne i mål?
