### ISSUE TITLE
Artsside - begrunnelse for feilbestemte arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#782]
Vi har fått en ny AlienSpeciesCategory: tidligere feilbestemte arter. Disse har et tekstfelt knyttet til seg som skal vises under begrunnelse.

Følgende må legges til i koden:
For arter hvor AlienSpeciesCategory == "MisIdentified", så skal fritekstfeltet MisIdentifiedDescription vises under begrunnelse.

Eksempelart: Arnica mollis.

**Comment by helemork** [comment]
Eksempelarten dukker ikke opp i lista når jeg søker. Er det noe som ikke er synkronisert eller lagt til ennå?

**Comment by AneMarlene** [comment]
> Eksempelarten dukker ikke opp i lista når jeg søker. Er det noe som ikke er synkronisert eller lagt til ennå?

Hvis du sletter cache i web-prosjektet, så vil den dukke opp :)
