### ISSUE TITLE
Vis kun Svalbard-kartet når det er arter på Svalbard.

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#801]
Kartene inne på vurderingssiden skal ikke vise fastlands-Norge når det er vurderinger for Svalbard.

**Comment by helemork** [comment]
Vi har et eget kart for Svalbard, som ligger under i rødlista partials. Dette skal ikke justeres så er bare å kopiere fila rett over.
Og den må kopieres da RL har andre fargekategorier og slikt. Dette kan du fint ta, @matssa
