### ISSUE TITLE
Artsside - datasett knyttet til vurderingen.

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#814]
Datasett som er lastet opp i vurderingen må gjøres tilgjengelig. @steinho kan kanskje  peke oss i rett retning?

**Comment by steinho** [comment]
Er på ballen her: https://github.com/Artsdatabanken/assessments-frontend/tree/feature/issue814

Har allerede lastet opp vedlegg til storageaccount og det er nok naturlig heim for dem - men skal revurdere katalogstruktur...

**Comment by steinho** [comment]
Data er kommet inn

Oppfølging knytt til visning  i #871

**Comment by steinho** [comment]
Har sjekket koden og ser ut som nye vedlegg er erstatning for vedlegg alltid for ny id - derfor 'trygt' å annta at vi kan forenkle opplasting av vedlegg til bare laste opp de id'ene som mangler i blobstorage
