### ISSUE TITLE
Forbedre kart med tabeller/legende

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#834]
Relatert til #900

Forsøk å kombinere dette: 
![image](https://user-images.githubusercontent.com/15391193/211761327-ebcc7243-16a6-43eb-a98d-00e8b5e54eee.png)
 med dette: 
![image](https://user-images.githubusercontent.com/15391193/211761485-a705f316-daa5-44ca-91f1-ffebb21839a6.png)
på en god måte. Poenget er at det skal være lett å forstå.

**Comment by helemork** [comment]
@AneMarlene Svar her når dere har bestemt om nåtid kan slås sammen til et kart med to farger, kjent og antatt, og antatt fargen være lik for de da to kartene som er relevante.
