### ISSUE TITLE
Inngangssiden - Tekst som tilhører innsynet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#857]
På inngangssiden må vi få inn noe tekst som omhandler innsynet. Teksten som skal inn er i vedlagte dokument og må ligge over søkefeltet. Teksten skal selvsagt bare ligge der i en begrenset periode (vi tar den bort når innsynet stenger). 

[Tekst til innsynssiden.docx](https://github.com/Artsdatabanken/assessments-frontend/files/10410397/Tekst.til.innsynssiden.docx)

**Comment by helemork** [comment]
Lurte på om kanskje teksten om hvordan å benytte siden bør være andre steder. 
Ihvertfall med den lengden den har nå.
Hvordan å legge igjen kommentarer bør f.eks ikke være på forsiden, men i forbindelse med feltene for å legge inn kommentarer.

**Comment by AneMarlene** [comment]
Mulig det siste punktet burde vises både på artssiden og på inngangssiden, men trooor vi vil se hvordan det blir på inngangssiden før vi er enig i at det skal sløyfes. Fint for brukeren å få all informasjonen samlet før hen setter i gang.
