### ISSUE TITLE
Bekreftelse av epost adresse, endring på tekstene

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#860]
- [x] Endre info som gis når man har fylt inn navn og epost. Per nå stå det: "Du vil bli tilsendt en epost (til ....)" Dette tekst kan erstattes med "Du vil bli tilsendt en epost (til XXX) som brukes for å bekrefte e-post adressen og med lenke for tilbakemelding."
- [x] Epost som bli sendt: Tittel: "Bekreftelse av e-postadresse for tilbakemelding"
Selve epost; "Klikk på lenken nedenfor for å bekrefte din epost adresse. Dette gi deg tilgang til å gi tilbakemelding på Fremmedartsvurderinger i 2023." + lenke!

- [x] avsender bør være "noreply@artsdatabanken.no"

**Comment by eirikn-artsdatabanken** [comment]
@EveliinaP burde vi kanskje også ta med noe sånt som "Dette er en automatisk generert e-post som du ikke kan svare på." tilslutt?

**Comment by helemork** [comment]
Litt spørsmål om innlogging/utlogging/tilbakemeldingssystemet.

Det står du blir sendt tilbake og kan nå legge igjen tilbakemelding... antar det er en eller annen innloggingsprosess? 
Men hvordan er det om folk vil legge inn tilbakemelding i flere runder, flere nettlesere, eller flere enheter? 
Får de en egen hash som slenges på lenken f.eks? Hvordan får de denne med seg rundt? Og hvordan logger de seg isåfall ut igjen om enheten deles med andre? I teorien kan de jo da dele denne (f.eks ved en feil) og andre skrive tilbakemeldinger i deres navn... Og er vi sikker på at vi har satt det opp slik at en slik eventuell hash eller whatnot alltid blir med når de klikker rundt på siden på forskjellige lenker? (F.eks tilbakelenkene)

Forstår ønsket om noe raskt, enkelt og effektivt, men vi må passe på at dette ikke går på bekostning av personvern og praktikaliteter. Så @eirikn-artsdatabanken @Myrdrahl og @steinho - hva er egentlig konseptet, og er vi sikker på at det er godt nok gjennomtenkt? Hvis svaret er ja - supert, men da må vi nok ha på plass en liten setning til eller to i forklaringstekstene i #857 slik at brukerne ikke stiller de samme spørsmålene som meg om f.eks at lenken er personlig og ikke må deles osv osv.

**Comment by EveliinaP** [comment]
@eirikn-artsdatabanken Ja til om automatisk e-epost settning i tillegg!
@helemork  ja, god poeng. Jeg tenkt litt samme når jeg endte opp og lage to brukerne men fant ikke måte å logge meg av. Dette er nok noe mer teknisk som dere må finne ut av men jeg kan teste etterhvert.
