### ISSUE TITLE
Nullsjekk mangler på ScoreInvasionPotential og ScoreEcologicalEffect (RiskMatrix)

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#866]
![image](https://user-images.githubusercontent.com/69149042/212668071-f1ae9fef-72d9-443d-9c0d-68ade7d0be94.png)

koden feiler når en vurdering mangler verdi på feltet "ScoreInvasionPotential" - det gjelder antagelig også "ScoreEcologicalEffect"

fe.ks vurdering med id 519: https://localhost:44321/fremmedartslista/2023/519

disse feltene er nullable int i datamodellen, virker som man enten må legge til nullsjekker eller endre datamodellen slik at disse ikke er nullable, men har standard med "0" som verdi (om mulig)

![image](https://user-images.githubusercontent.com/69149042/212668670-706023cb-0c22-48a7-a18e-11e92301158a.png)

koden ligger i _RiskMatrix.cshtml https://github.com/Artsdatabanken/assessments-frontend/blob/951e6f4849f8a22ff61e1760733c56758f88430a/Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskMatrix.cshtml#L31

**Comment by AneMarlene** [comment]
Risikomatrisen skal kun vises for arter som _er_ risikovurdert -dvs. arter som har Category != "NR". Om ikke vil matrisen feile, ikke bare for selve skåren, men også for usikkerheten. @helemork fikser du slik at risikomatrisen kun vises for risikovurderte arter?
