### ISSUE TITLE
Artside - formatere visning av datasett som er knytt til vurderingen

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/assessments-frontend#871]
Vedlegg har et filnavn, (minetype) og en kort enkel beskrivelse.

Kan være ingen eller flere...

- [x] Lenke til vedlegg bør åpner i ny fane - slik at filen lastes ned uten å gå bort fra vurderingen
- [x] Plassering - rett over referanser
- [x] tabell/liste o.l.

![image](https://user-images.githubusercontent.com/3253353/212835785-a41e0b6e-7909-4fe7-80bc-82014f6e3710.png)

**Comment by EveliinaP** [comment]
Vise vedlegg(ene) i en tabell der fil navn, beskrivelse og lenke er delt i egne kolonner. Da bli lenke som er lagt inn per nå plasert i tabellen. I tillegg skal Filvedlegg flyttes lengre ned slik at den ligger rett ovenfor "Sitering". 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/epk/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/epk/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/epk/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=NO-BOK style='tab-interval:35.4pt;word-wrap:break-word'>




Fil navn | Beskrivelse | Lenke for å laste ned
-- | -- | --
  |   |  
  |   |  
  |   |  




</body>

</html>
