### ISSUE TITLE
Artsside - Spredningsmåter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#885]
For risikovurderte arter skal spredningsmåter arten har til Norge, til natur og i natur formidles. Dette er viktig bakgrunnsdata som ofte brukes av bl.a. forvaltning. 

Se dokument for foreslått oppsett og innhold, blå og grønn tekst skal altså ikke vises på siden, men er hjelpetekst  :)

[Artsside_Spredningsmåter.docx](https://github.com/Artsdatabanken/assessments-frontend/files/10466036/Artsside_Spredningsmater.docx)

**Comment by helemork** [comment]
hvorfor faner og ikke heller hovedoverskrifter under hverandre? Det er litt uryddig å ha forskjellige faner på forskjellige arter, 
og for mange faner gjør innholdet mye mer utilgjengelig. Vi er allerede inni en ekspandert boks.
Så med mindre tabellene er mer enn 20 linjer for hver av dem vil det være unødvendig mye ekstra trykk for å få det frem?
Omtrentlig hvor store er tabellene? 
Har du noen gode eksempelarter for disse dataene?

OG: er det ikke bedre å eventuelt ha en se mer hvis det skulle bli alt for mye, enn å skjule alt i starten?
Jeg spør da jeg ikke kjenner dataene i dette spesielt godt.

**Comment by AneMarlene** [comment]
Bare legg det under hverandre i stedet for faner (som vi snakka om på arbeidsmøtet). :) 

Eksempelarter: sitkagran (har import) og dvergmus (har ikke import). 

Det er sjeldent veldig mange rader per tabell her. Antagelig få som har mer enn 10 rader i en tabell.
