### ISSUE TITLE
Formuleringer: Hva forklarer artens risikokategori?

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#890]
I artenes vurderingsider har vi behov for ekstra forklaringstekst for "Hva forklarer artens risikokategori". Dette bør komme synlig under tittelen når man trygger på vis mer knappen. Tekst (for alle arter): "Artens risikokategori bestemmes av artens skår på to akser, invasjonspotensial (x-aksen) og økologisk effekt (y-aksen)."
![bilde1](https://user-images.githubusercontent.com/25793207/213434976-bc1d6958-83ca-4246-bd63-5e8d83ff9ecb.png)

**Comment by helemork** [comment]
Står ikke dette sammen med risikomatrisen?
Betyr det at risikomatrisen skal flyttes inn i denne boksen?

**Comment by EveliinaP** [comment]
Enig at dette er egentlig tekst som forklarer matrisen men matrisen kan stå synlig lenge opp men denne teksten må komme her i tillegg for å forklare informasjon som kommer under "Hva forklarer artens risikokategori".  Så risikomatrise skal ikke flyttes.

**Comment by helemork** [comment]
Hvis ikke matrisen og x/y-aksene er med inn i denne boksen tror jeg det er lurt å holde oss til å snakke om invasjonspotensial og økologisk effekt, ikke blande inn aksene i introduksjonen. Hvis de skal med, så flytt det heller under overskriften for hver akse (se eksempel nedenfor). Det gir veldig mening å nevne dem i forbindelse med beskrivelse av risikomatrisen og utregningene, men ikke i et annet avsnitt som en introduksjon langt borte fra tabellen de tilhører.

Det som derimot hadde vært veldig informativt er å nevne hvilke kriterier som faller under henholdsvis invasjonspotensiale og økologisk effekt, for det mangler i denne fanen. Som utenforstående er informasjonen jeg savner noe mer i denne gaten:

"Artens risikokategori bestemmes interaksjonen mellom dens invasjonspotensial og dens økologiske effekt."  (bare bedre formulert)

Under overskriften for Invasjonspotensiale ville jeg lagt til noe isj sånn:
"Invasjonspotensiale omfatter kriteriene A - median levetid, B - Ekspansjonshastighet og C - kolonisering av natyrtype. I risikomatrisen fremstilles disse på x-aksen i risikomatrisen i figur (figurtall), hvor de rangeres fra lav til høy i fire steg." (eller noe sånt).

Arten er vurdert til å ha et stort invasjonspotensiale (skår på 4)
Utslagsgivende kriterier for invasjonspotensiale er... 
* A. Median levetid i Norge på minimum 650 år . [se utregning-knapp]
* B. Ekspansjonshastighet på minimum 500 m/år (med usikkerhet ned mot mellom 160 og 499 m/år ). [se utregning-knapp]"

og tilsvarende for økologisk effekt.
