### ISSUE TITLE
Forklaringstekster: Hva forklarer artens risikokategori og avgjørende kriterier

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#891]
Under "Hva forklarer artens risikokategori" er det fane for "Avgjørende kriterier". Det skal ha forklaringstekst: "Kriteriene arten skårer høyest på for hver av de to aksene. Les mer om kriteriene". (Les mer om kriterier skal være lenke når vi har nettside ferdig for det..kommer senere).  
Unntak for tekst er NK arter og da skal teksten være: "Arten er vurdert til ingen kjent risiko NK og har dermed ingen avgjørende kriterier."

![bilde2](https://user-images.githubusercontent.com/25793207/213437729-ec199b74-02c8-42fd-ad4c-fd738d0551fd.png)

**Comment by matssa** [comment]
For arter som er vurdert til NK har vi allerede en tekst. Skal denne byttes ut? 
![image](https://user-images.githubusercontent.com/15391193/213483163-ea57e38a-c50f-46d0-a01e-5a6217cb2564.png)

**Comment by EveliinaP** [comment]
Du så sikkert ikke men det stå oppdatering av den teksten for NK arter i kommentar, det skal oppdateres til: "Arten er vurdert til ingen kjent risiko NK og har dermed ingen avgjørende kriterier."
