### ISSUE TITLE
Formuleringer: Klimaeffekter

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#895]
I artenes vurderings side er det boks om "Klimaeffekter". 
- [x] Navn på denne boksen skal byttes til "Effekt av klimaendringer"
- [ ] Det er fire forskjellige utfall kombinasjoner basert på to spørsmål. Disse har egne tekster som skal oppdateres til disse: 
* Delkategori invasjonspotensiale ==yes & delkategori økologisk effekt==no ; Artens invasjonspotensial ville ha vært lavere (målt som endring i delkategori) i fravær av  klimaendringene.   
Den økologiske effekten ville _ikke_ ha vært mindre (målt som endring i delkategori) i fravær av klimaendringene.      
* Delkategori invasjonspotensiale ==no & Delkategori økologisk effekt==yes; Den økologiske effekten ville ha vært mindre (målt som endring i delkategori) i fravær av klimaendringene.    
Artens invasjonspotensial ville _ikke_ ha vært lavere (målt som endring i delkategori) i fravær av  klimaendringene.      
* Delkategori invasjonspotensiale ==yes & delkategori økologisk effekt==yes ;     Både den økologise effekten og invasjonspotensialet ville vært lavere (målt som endring i delkategori) i fravær av klimaendringene. 
*  Delkategori invasjonspotensiale ==no & delkategori økologisk effekt==no; Verken økologiske effekter eller invasjonspotensial ville vært lavere (målt som endring i delkategori) i fravær av  klimaendringene.
- [ ] Om eksperten har valgt ja på en av de svarene og har skrevet noe i fritekst felt så skal dette tekst vises slik som er per i dag under tittelen "Betydningen av klimaendringer:". Om det ikke er skrevet noe fritekst skal dette "Betydning.." del skjules.

**Comment by helemork** [comment]
"Effekt av klimaendringene"  impliserer eksisterende kjente klimaendringer, er dette tilfellet? Eller tenker vi mer på effekt av potensielle fremtidige antatte klimaendringer? Isåfall bør det kanskje vøre "Effekt av klimaendringer" (ubestemt form). Kan kanskje være flere effekter også, ikke bare én? Eller tenker vi på invasjonspotniale og økologisk effekt som en samlet effekt og derav entall?

**Comment by EveliinaP** [comment]
@olgahil er kanskje beste at du Olga ta stilling til kommentar fra Helene.

**Comment by steinho** [comment]
> Effekt av klimaendringer 

"Effekt av klimaendringer" er ok
