### ISSUE TITLE
Formuleringer: Geografisk variasjon i risiko

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#896]
I artenes vurderingsside er det boks om "Geografisk variasjon i risiko". Om eksperten har valgt IF geografisk variasjon i risiko == yes, da skal det vises tekst: "Arten har geografisk variasjon i risiko, og kunne fått lavere risikokategori enn [xx-XX] i deler av sitt potensielle forekomstareal.       Dette skyldes at: ... " Tekst som kommer etter "Dette skyldes at:" er det eller de tekstene som er valgt av eksperten (f.eks. "Artens evne til reproduksjon og/eller spredning er begrenset til visse kystvannssoner eller seksjoner"). xx-XX Er artens risikokategori slik som er allerede vist i dag.
Om eksperten har valgt IF geografisk variasjon i risiko == no, da skal det vises tekst: "Arten er antatt å ha lik risikokategori i hele sitt potensielle forekomstareal.". Og ingen ekstra info om "hva dette skyldes at" trengs.

**Comment by matssa** [comment]
Oppdatert teksten, men ser GeographicalVariationMarine mangler helt her. Vi har kun tilgang på GeographicalVariation. Hører med @AneMarlene om dette er noe som bør inn.

**Comment by EveliinaP** [comment]
Høres som god plan!
