### ISSUE TITLE
Formuleringer: Utbredelse/ Regional naturvariasjon

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/assessments-frontend#897]
I artenes vurderingsside i utbredelses boks og regional naturvariasjon fane ønsker vi forklaringstekst under overskrift for sider med vurderingsområde= Fastlands-Norge og = Svalbard:  "Bioklimatiske soner og seksjoner hvor arten finnes i dag eller antas å kunne finnes i fremtiden (innen 50 år)."
IF ikke utfylt da skal tekst være: "Det er ingen bioklimatiske soner eller seksjoner angitt for denne arten."

**Comment by matssa** [comment]
Når det gjelder vurderingsområde brukes feltet "EvaluationContext". Det kan bare ha to verdier: N -> "Fastlands-Norge med havområder" eller S -> "Svalbard med havområder". Vi har ingen måte (eller har vi det @AneMarlene?) å finne kun fastlandsvurderinger på.

**Comment by EveliinaP** [comment]
Unskyld, her er det Fastlands-Norge med havområder som vi snakker om. Så det er bare bruke de S og N.

**Comment by AneMarlene** [comment]
Litt vanskelig å avgjøre om denne er som den skal være eller ikke når vi ikke har lagt inn selve dataen her enda. Får se om vi rekker å få inn tabellene til innsynet. Tekstene er ok, men for marine arter er det kystvannsoner og -seksjoner som vises her. For arter som er utelukkende marin (ikke i kombinasjon med terrestrisk), burde derfor teksten være "Kystvannsoner og -seksjoner hvor arten finnes i dag eller antas å kunne finnes i fremtiden (innen 50 år)."
