### ISSUE TITLE
Nytt felt "SpeciesGroup" i API

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#90]
Som vi var litt innom på møtet tirs 24.8. er det ønskelig at det i transformeringen legges til et felt for artsgruppe som representerer den taksonomiske inndelingen i artsgrupper. Det kan gjerne kalles SpeciesGroup.  Ser ut som _Ekspertgruppe_ i API'et pr. nå har blitt splitta, så du har nok allerede oppskriften. Men vi vil altså gjerne ha med opprinnelig informasjon i Ekspertgruppe/ExpertCommittee ut i API'et. Ja takk begge deler =) Det som blir å hete ExpertCommittee er på en måte navnet på teamet som gjorde vurderingene. 

Altså: vurderingene av den taksonomiske gruppen _SpeciesGroup_ "vårfluer" er utført av ekspertkomité _ExpertCommittee_ "vårfluer, steinfluer, døgnfluer, øyenstikkere". Om vi har med begge deler blir det bedre samsvar med navnene vi har på ekspertkomitéene andre steder (artskapitler m.m.).

Vurderingsområde (Norge/Svalbard) skal ikke være med, f.eks: Karplanter (Norge) -> Karplanter

**Comment by eirikn-artsdatabanken** [comment]
@KristineLund har vi en kort og fin beskrivelse på engelsk for det nye feltet?

**Comment by KristineLund** [comment]
> @KristineLund har vi en kort og fin beskrivelse på engelsk for det nye feltet (til dokumentasjonen)?

Tja, kanskje "Group the species belongs to, in most cases a taxonomic group" ellernosånt?
