### ISSUE TITLE
Artsside - topp - utslagsgivende kriterier og geografisk variasjon info

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#913]
Til høyre for matrisen skal vi ha inn nøkkelinformasjon om vurderingen: Kategori og utslagsgivende kriterier, samt om arten har geografisk variasjon i risiko (det sistnevnte er ønsket at skal løftes fram bedre av flere brukergrupper). 

Se vedlegg for mer info og snacks. 

[Artsside_topp_kriterieoppsummering_gjenstående_utslagsgivende_kriterier.docx](https://github.com/Artsdatabanken/assessments-frontend/files/10510963/Artsside_topp_kriterieoppsummering_gjenstaende_utslagsgivende_kriterier.docx)

**Comment by helemork** [comment]
Har lagt inn hvilke kategorier usikkerheten dekker i kommentarene. 
Fant ingen eksempler med tre kategorier, så om de finnes, test at jeg har gjort rett der :)
Se videre kommentarer inline.

![bilde](https://user-images.githubusercontent.com/17450081/216636225-b617925e-829f-49c2-aa2c-c57569488f46.png)

**Comment by AneMarlene** [comment]
@matssa Når du begynner med denne, kan du kanskje fikse to ting på setningen om kategori: 
1. kategori i tekstform før forkortelse/kode, altså ingen kjent risiko - NK
2. tekst for ev. usikkerhetskategori skal også i kursiv, altså _ingen kjent risiko_
3. kategori i tekstform skrives med liten forbokstav når det er i en setning, altså ikke "I" i "ingen", men "i".
![image](https://user-images.githubusercontent.com/58254444/219596168-4eab8ffb-1d7e-4165-9c17-d5f570285be9.png)
