### ISSUE TITLE
Layout: Legg til tilbake til topp-knapp :)

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/assessments-frontend#918]
alternativ 1: dump dem i en div som samler dem sammen h2 på hver overskrift. Veldig forutsigbart og vanlig i gamle dager, ligger en inne op ekspertoppsumeringen i branch layout nå.
Den bør selvfølgelig se mer smashing ut med pil opp og sånn.

Alternativ 2: 
Følg mer moderne stil med én sticky knapp i nedre høyre hjørne når man scroller forbi første skjerm. Da er det veldig viktig å passe på at den IKKE ligger oppå noe innhold... spesielt på mobil. Ikke et problem for større skjermer.

Vil jo si det er ryddigst med alt 1, men de lærde strides på denne.

**Comment by matssa** [comment]
Lukker denne nå som vi har table of contents som sticky på siden.
