### ISSUE TITLE
Artsside - Risikomatrise - endre type objekt for å bedre utseende

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#922]
Risikomatrisen ser penere ut om alle cellene/rutene ser like store og kvadratiske ut. Nå er rutestørrelsen noe avhengig av tekstlengden på aksene - noe som har å gjøre med at risikomatrisen er lagret som en tabell. Vi ønsker en fin og fjong matrise <3 

![image](https://user-images.githubusercontent.com/58254444/216297871-691ddcbd-7a70-48ef-85f6-ffb5d6cf2d75.png)

**Comment by helemork** [comment]
Denne ble fikset i #924
