### ISSUE TITLE
Artsside - matrisebug

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#931]
Jeg får nå en warning når jeg bygger lokalt hos meg. Den peker på risikomatrisen: 

![image](https://user-images.githubusercontent.com/58254444/216768808-ca1251e1-207b-444b-a8d4-5e6ba818167f.png)

Bør den bare slettes eller ev. byttes ut med noe annet? 
![image](https://user-images.githubusercontent.com/58254444/216768865-6b4d3662-59ee-459f-8033-ec394f114614.png)

**Comment by helemork** [comment]
akk, dette var litt juks fra min side. 
om man endrer den til li, så listes den opp for brukere som har avskrudd styling. Men vi trenger et element til for å dytte på ting, så den var en enkel fiks.

Du har veldig streng setting om den feiler bygget pga en suboptimal nesting?
men ok. jeg kan fikse den :D
