### ISSUE TITLE
Eksport til Excel

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#94]
Data for vurderingene skal eksporteres til fil via nettsiden, man skal kunne filterere resultatet

Det gjøres på samme måte/sted som tabellen som viser data (listevisningen)

Oppskrift ligger i [Rødliste datamodeller.xlxs på teams](https://teams.microsoft.com/l/file/E2010A54-8D85-4422-B6F0-3E39B720607B?tenantId=97c30119-98d7-4b74-8ad7-0ba9a09a94c1&fileType=xlsx&objectUrl=https%3A%2F%2Fartsdatabankenno.sharepoint.com%2Fsites%2FProsjekt-Visningavekspertvurderinger%2FDelte%20dokumenter%2FGeneral%2FR%C3%B8dliste%20datamodeller.xlsx&baseUrl=https%3A%2F%2Fartsdatabankenno.sharepoint.com%2Fsites%2FProsjekt-Visningavekspertvurderinger&serviceName=teams&threadId=19:0f2a7091e2504f15b9ddbc5a995fca55@thread.tacv2&groupId=25d2b49f-a390-4a2f-97f0-6e1ebc13e0e2) - se arket "Eksporten"

man kan sikkert også finne feltnavn og kanskje gjenbruke noe logikk fra eksporten her: https://github.com/Artsdatabanken/Rodliste2019/blob/2e4b22a2ada910579790cc1358541f011cb20d92/Prod.Api/Controllers/ExpertGroupAssessmentsController.cs

**Comment by KristineLund** [comment]
@SnorresKongesaga har begynt på en spekk [her](https://artsdatabankenno-my.sharepoint.com/:w:/g/personal/kristine_bjornaas_artsdatabanken_no/EaC4VKyFX3BAm8sAN9RnuyEBGl2viguFKkg4zm5CLGoZ7w?e=Uu2WC5)

Vi bør tenke over om vi skal bruke de nye engelske feltnavnene fra SpeciesAssessment2021-transformasjonen og de tilhørende beskrivelsene på engelsk, eller om alt bør være på norsk. Eller skal vi ha to data-ark, ett på norsk og ett på engelsk, i tillegg til metadata-arket?

**Comment by SnorresKongesaga** [comment]
Vi bør ha norske feltnavn siden alt annet i eksporten er på norsk

**Comment by SnorresKongesaga** [comment]
Jeg har lagt fila [her](https://teams.microsoft.com/l/file/E2010A54-8D85-4422-B6F0-3E39B720607B?tenantId=97c30119-98d7-4b74-8ad7-0ba9a09a94c1&fileType=xlsx&objectUrl=https%3A%2F%2Fartsdatabankenno.sharepoint.com%2Fsites%2FProsjekt-Visningavekspertvurderinger%2FDelte%20dokumenter%2FGeneral%2FR%C3%B8dliste%20datamodeller.xlsx&baseUrl=https%3A%2F%2Fartsdatabankenno.sharepoint.com%2Fsites%2FProsjekt-Visningavekspertvurderinger&serviceName=teams&threadId=19:0f2a7091e2504f15b9ddbc5a995fca55@thread.tacv2&groupId=25d2b49f-a390-4a2f-97f0-6e1ebc13e0e2)

**Comment by SnorresKongesaga** [comment]
Da har jeg lagt til (forhåpentligvis) gode norske feltnavn og forklaringer i fila jeg lenker til over @eirikn-artsdatabanken

**Comment by KristineLund** [comment]
Ad "siteres som" i eksporten: 
![image](https://user-images.githubusercontent.com/25904198/134329474-a4b9b82f-3cab-4811-8489-ff1b59cd0bcc.png)
 Hvis årstall endres til "2021, 24. november" blir dette en kurant "siteres som"-mal for eksporten
