### ISSUE TITLE
Artsside - tekst pluss link for husdyrraser som vurderes

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#943]
brukerne vil ha inn en link til en oppklarende tekst når det gjelder vurdering av husdyrraser. Teksten passer inn rett under konklusjonen (uten egen tittel, men med luft mellom denne teksten og konklusjonen). Selve siden det skal linkes til er ikke lagt ut enda, så foreløpig må linken være død. 

Teksten som skal inn er: 
MERK: Vurderingen gjelder kun rasen [taksonnavn på 'forma'(latinsk + norsk)] og ikke [underarten/arten] [taksonnavn på taksonomisk nivå over formen]. Se her.

Her er et eksempel for en form på artsnivå (på underartsnivå er det altså "og ikke underarten..." som blir riktig henvisning):

![image](https://user-images.githubusercontent.com/58254444/217273762-f74fccda-212a-4917-90e8-300e5538c288.png)

**Comment by AneMarlene** [comment]
@steinho denne er muligens avhengig av at informasjon om form kommer med fra FAB. Muligens skulle TaxonHierarcy vært en tuple som inneholder taksonomsik nivå og navn på taksonomisk nivå. Da ville den vært enklere for Mats å bruke. F.eks. kunne et listeelement vært (helt tilfeldig valgt eksempel altså... :D ): 
[TaxonRank: "Genus",
TaxonRankName: "Passer"]

**Comment by steinho** [comment]
Dette er noe annet en vurdert som en del av? Man trenger bare en kobling mellom denne vurderingen og en annen vurdering? nameHiearchy er en liste med alle overordnede element og Rang - men inneholder ikke kobling til annen vurdering - så den må muligens lages manuelt i transformation . Men taksonomisk kategori ligge både på vurdeingen og de overordnede nivåene via namehiarchy
