### ISSUE TITLE
Fjerne innsynsspesifikk kode etter innsynet

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/assessments-frontend#946]
Når innsynsperioden er over må vi ta vekk fremmedartslista 2023 igjen, samt huske å fjerne spor etter innsynet i løsningen slik at det kan bli klart for den faktiske lanserignen til høsten.

**Comment by steinho** [comment]
Mulig det var en annen task på dette - men det vi diskuterte var å ha en config parameter som styrer om fab2023 vises eller ikke..... slik at vi ikke gjør kodeendringer - men slår av visningen....

**Comment by matssa** [comment]
Ja det stemmer, så det var litt upresist av meg dette. Det jeg mente var at vi må huske å fjerne alt som har med innsynet å gjøre før vi lanserer til høsten.
