### ISSUE TITLE
Artsside - hva forklarer artens risikokategori - tone ned "vis detaljer"

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#948]
Vis detaljer tar mye plass og oppleves rotete for brukere, samt at det stjeler fokus fra det som er viktig å få fram her - som bl.a. er selve verdien på kriteriene:

![image](https://user-images.githubusercontent.com/58254444/217479783-6a6e024c-aa15-4ac4-a565-4a2743ce4204.png)

Vi ønsker et oppsett ala det vist nedenfor tegnet av @helemork. Her kommer et forsøk forklaring, samt å knytte feltene til data. Tallene henviser til tall i skjermdumpen under:

1. Oppsettet (utseendemessig) ønskes likt på begge fanene (men innholdet for en gitt art vil selvsagt være ulikt mellom fanene. F.eks. vil ikke de samme kriteriene vises begge steder for en gitt art).
**1B.** Liten merknad: For NK-arter, så vises _ingen_ avgjørende kriterier. Da vises kun en setning på denne fanen "Arten er vurdert til ingen kjent risiko NK og har dermed ingen avgjørende kriterier.", mens all kriterie-info er på fanen Øvrige kriterier. Se ID 1864 (praktedelgran).
2. Ordet henviser til tekstene/displayname på matrisens x-akse. I fila _RiskMatrix.cshtml hentes de ut slik: @Model.Assessment.ScoreInvasionPotential.DisplayName().ToLowerInvariant()
3. Selve skåren på aksen i tallformat. Dette er objektet (int)ScoreInvasionPotential på modellen [husk å caste til int!]
4. Hvilke kriterier det er som listes opp her avhenger av hvilke kriterier det er som er utslagsgivende. Har aksen Invasjonspotensial ingen utslagsgivende kriterier ((int)ScoreInvasionPotential == 1 & Category != "NK"), så listes ingen avgjørende kriterier opp, og det står (slik som det gjør nå i slike tilfeller, med unntak av at jeg nå fjernet ordet "brukte" i setningen:) "Arten har lite invasjonspotensial og har dermed ingen utslag på kriterier på invasjonsaksen. Se fanen Øvrige kriterier.". Eksempelart for dette siste tilfellet er ID 1438 (amerikansk bjørkepraktbille). Her ser du at både A, B og C er listet opp under Øvrige kriterier.
5. Selve verdien arten har på det gitte kriteriet (inklusive usikkerhet om den har det - det blir det f.eks. under Øvrige kriterier for A-kriteriet på ID 1438 (amerikansk bjørkepraktbille)). Verdiene hentes ved hjelp av funksjonen CriteriaDescription(criterion.CriteriaLetter, criterion.Value) brukt i GetLetterFullText() nå.
6. Skåren på kriteriet i tallformat (kan ta verdiene 1, 2, 3 eller 4). Eksempel for A-kriteriet: Feltet som i eksemplet gir tallet 4 på A er uncertaintyA.Value (dette er hva det kalles frontend og stammer fra lista "Criteria" på modellen. Mer presist er det listeobjektet Value for CriteriaLetter == "A". Altså Criteria.Value for CriteriaLetter == "A". Samme logikk for de andre kriteriene. 
7. Selve knappene (med innhold) som erstatter det som ligger under "Vis detaljer" for hvert kriterium nå. Innholdet beholdes som det er. For å se på et par arter med ulikt type innhold er ID 2831 (sørhare) og ID 601 (platanlønn) og  ID 337 (Aedes (Stegomyia) albopictus) gode eksempler tror jeg. 
8. Ordet henviser til tekstene/displayname på matrisens y-akse. I fila _RiskMatrix.cshtml hentes de ut slik: @Model.Assessment.ScoreEcologicalEffect.DisplayName().ToLowerInvariant()
9. Selve skåren på aksen i tallformat. Dette er gis av objektet (int)ScoreEcologicalEffect på modellen [husk å caste til int!]
10. Hvilke kriterier (D-I) det er som listes opp her avhenger av hvilke kriterier det er som er utslagsgivende. På fanen *Øvrige kriterier* har vi nederst her også en oppsummerende setning som forteller brukeren hvilke kriterier det er som _ikke_ har data - de er altså vurdert som usannsynlige. F.eks. på ID 337 (Aedes (Stegomyia) albopictus) kan du se at den slik "Økologiske effekter etter kriterium F, G, H, I er vurdert som fraværende (usannsynlige).". Har aksen Økologisk effekt ingen utslagsgivende kriterier ((int)ScoreEcologicalEffect == 1 & Category != "NK"), så listes ingen avgjørende kriterier opp, og det står (slik som det gjør nå i slike tilfeller): "Arten har ingen kjent økologisk effekt og har dermed ingen utslag på kriterier på effektaksen.". Se gjerne ID 669 (fjelledelgran) for eksempel på hvordan dataen på de to fanene ser ut da. 

![image](https://user-images.githubusercontent.com/58254444/228501905-394338b4-7338-42a7-90cc-cccad51e20fe.png)

**Comment by helemork** [comment]
Dette har jeg en plan på, så fort @matssa er ferdig å tukle i den partial'en for å unngå for mye konflikter :)
