### ISSUE TITLE
Datagrunnlag for statistikk

### ISSUE THREAD

**Issue by eirikn-artsdatabanken** [Artsdatabanken/assessments-frontend#96]
Legge ferdig utregnet data for statistikk som skal vises på listesiden - #42

- [x] (1) Antall per kategori (obs: kategorier med gradetegn: for dette formålet kan VUº = VU) NS er en "fake" kategori, vi får finne utav hvor det kommer fra

- [x] (2) Antall per gjeldende kriterie (A, B, C, D, E) Dette er kun relevant for arter i kategoriene CR, EN, VU og NT (trua og nær trua arter). I eksporten fra Rødlistebasen ligger gjeldende kriterier i kolonna "Kriterier2021" som en tekststreng (antar jeg), eks. "A2(c)+3(c)+4(c); B2a((i))b(ii,iii,iv); C1+2a(i)" - her er A, B og C alle gjeldende hovedkriterier, dvs. hovedkriteriet er det eneste m stor bokstav. (PS1: Siden en art kan ha flere gjeldende kriterier blir ikke totalsummen lik antall CR, EN, VU og NT- arter, men det er ok, PS2: en vurdering kan ha flere kriterier helt eller delvis utfylt, men alle er ikke nødvendigvis utslagsgivende for kategori, derav utheving. Men om du går etter "Kriterier2021" blir det riktig.)

- [ ] (3) Antall per hovedhabitat bør nok hentes ut kun for arter i kategoriene CR, EN, VU og NT. Det kan ligge info her på vurderinger i andre kategorier også, men det har vært valgfritt å fylle i for ikke-"trua eller nær trua" arter, så infoen der er ikke nødvendigvis kvalitetssikra. En vurdering/art kan ha flere hovedhabitat, så summen blir større enn totalen av vurderinger.

- [ ] (4) Antall per påvirkningsfaktor (høyeste nivå av påvirkningsfaktor-stien, eks. "Påvirkning på habitat") -bør nok hentes ut kun for arter i kategoriene CR, EN, VU og NT. Selv om det finnes flere former av eks. "Påvirkning på habitat" på en vurdering, bør den kun telles én gang per vurdering.

- [ ] (5) Antall per region/havområde (basert på "kjent" forekomst) -bør nok hentes ut kun for arter i kategoriene CR, EN, VU og NT

**Comment by KristineLund** [comment]
Fortsetter i #42
