### ISSUE TITLE
Artsside  - tekst som angir at arter vurderes sammen, og med hvilket takson

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#960]
Innhold kommer...

**Comment by EveliinaP** [comment]
I tilfeller der flere arter har samme vurdering skal hver har sitt egen vurderingsside (selv om det viser samme informasjon), men det skal vises hvilke andre arter som er vurdert sammen med. Dette informasjon kan legges under artsnavn med tekst "Vurderes sammen med xxx". Dette er likt uavhengig av hvor mange arter som har blitt vurdert sammen (artA, artB, …). Font størrelse kan være litt mindre enn for arten som side gjelder og om det er flere arter kan navnene deles i flere rader. Bare  vitenskapelignavn på arter som er vurdert sammen, ikke populærnavn.
![image](https://user-images.githubusercontent.com/25793207/219323167-2b1d5d65-20db-4577-8b4f-cc48e06b8ea2.png)

**Comment by matssa** [comment]
Her trenger vi litt hjelp til å finne alle relasjoner @steinho. Mulig det må inn i transformeringen. I mange til mange-relasjoner eksisterer ikke alle relasjonene. Dette ligger på objektet connectedTaxon i FAB, men skulle kanksje vært en liste med objekt i stedet?

**Comment by AneMarlene** [comment]
@matssa Da har Stein gjort den jobben du etterspurte, og du finner infoen i ConnectedTaxons :) Issuet er endelig ready for take off 😎
