### ISSUE TITLE
Artsliste - får ikke åpnet arter uten artsgruppeikon (bilde)

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/assessments-frontend#979]
Det smeller når man prøver å gå inn på en art som mangler bildet for artsgruppa. Eks. Acartia tonsa. 

![image](https://user-images.githubusercontent.com/58254444/219373836-9c2b1790-ac07-4cf5-9266-1a6bf6313697.png)

**Comment by matssa** [comment]
Den aktuelle vurderingen mangler artsgruppe.
