### ISSUE TITLE
Plassering av årsak til endring og årsak til nedgradering

### ISSUE THREAD

**Issue by KristineLund** [Artsdatabanken/assessments-frontend#99]
Se på hvor på visningssiden vi skal legge til info som beskriver årsak til kategoriendring (fra forrige rødliste) _ÅrsakTilEndringAvKategori_/ReasonCategoryChange og årsak til ned/oppgradering pga populasjoner i naboland.

Felter i modellen: RationaleCategoryAdjustment, ReasonCategoryChange, ExtinctionRiskAffected, CategoryAdjustedFrom.

eksempelart med endret kategori: 32041
![image](https://user-images.githubusercontent.com/25904198/131511601-ee1376e3-86d4-4160-bc41-a4e67dcf3667.png)

eksempelart med nedgradert kategori: 31847
![image](https://user-images.githubusercontent.com/25904198/131511793-63408d97-8b2d-48be-9182-6e625882140f.png)

**Comment by KristineLund** [comment]
På innsynet la vi f.eks. til standardfraser (rød strek) og deretter RationaleCategoryAdjustment (tekstfelt). Det kan bli litt repetisjon av konklusjonen i oppsummeringa, men ikke alltid.
<img width="416" alt="Nedgradering" src="https://user-images.githubusercontent.com/25904198/131833001-fe14009a-f7ee-4eb6-b0d3-73c5fc01982f.png">

**Comment by helemork** [comment]
Ok, Nå har bolkene med tekst mer eller mindre kommet på plass, trenger gjerne mer gjennomlesing etterhvert. Midlertidig er alt puttet sammen under kapittelet "detaljer".

Når jeg har sett på hva som er inneholdt i de forskjellige synes jeg det vil virke litt rart å plassere degradering rett under ekspertuttallelsen. Dette fordi det i stor grad er ren oppsumering av det samme de ofte har som konklusjon, men også fordi leseren på dette tidspunktet ennå ikke har sett noe av det andre som sier hvorfor arten skal plasseres der den gjør. Jeg synes det derfor hadde passet mer sammen med kriteriene, da nedgradering tross alt er en nedgradering av det man har "regnet seg frem til" før man lander på en endelig konklusjon. Litt sånn "kriteriene sier sånn, meen så kom dette så da ble det sånn". 

Historikken og margen er allerede litt knotete mtp. mobil og å putte mer i margen er jeg litt skeptisk til, da de egentlig er rene  lenker ut til tidligere vurderinger. Det ble uttrykt et ønske om å  holde sidemenyen der til utadgående data/lenker. Jeg tenker det derfor hører sammen i hoveddelen. Men jeg mener det meste i dette avsnittet (generasjonstid, populasjonandeler og inkluderingskriterier kanskje bør grubles litt på hvor bør bo. Så jeg anser dette som et midlertidig hjem til vi har tenkt litt mer.
